dist: xenial
language: cpp
sudo: false
branches:
  except:
    - /^(wip\/)?(appveyor|msvc|mingw|windows)(\-.+)?$/

addons:
  apt:
    sources: &default_sources
      - ubuntu-toolchain-r-test

matrix:
  include:
      # clang-5.0 is the default installed on travis VMs
    - compiler: clang-default
      env: TRUE_CC=clang TRUE_CXX=clang++
    - compiler: gcc-4.9
      env: TRUE_CC=gcc-4.9 TRUE_CXX=g++-4.9
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - gcc-4.9
            - g++-4.9
    - compiler: gcc-6
      env: TRUE_CC=gcc-6 TRUE_CXX=g++-6
      addons:
        apt:
          sources:
            - *default_sources
          packages:
            - gcc-6
            - g++-6
    - compiler: clang-6.0
      env: TRUE_CC=clang-6.0 TRUE_CXX=clang++-6.0
      addons:
        apt:
          sources:
            - *default_sources
            - llvm-toolchain-xenial-6.0
          packages:
            - clang-6.0
            - clang++-6.0

before_install:
# Travis will set CC and CXX after the env commands specified in the matrix are run, overwriting whatever
# we've specified there, so we need to reset them here. See also https://github.com/travis-ci/travis-ci/issues/6633 .
  - CC="${TRUE_CC:-$CC}"
  - CXX="${TRUE_CXX:-$CXX}"


script:
- lscpu
- set -e && echo "CC is ${CC}, CXX is ${CXX}" && ${CC} --version && ${CXX} --version
- make
- ./check-gold.sh
- ./robsize 0 --superfast
