
asm.bin:     file format binary


Disassembly of section .data:

0000000000000000 <.data>:
   0:	66 90                	xchg   ax,ax
   2:	66 90                	xchg   ax,ax
   4:	66 90                	xchg   ax,ax
   6:	66 90                	xchg   ax,ax
   8:	66 90                	xchg   ax,ax
   a:	66 90                	xchg   ax,ax
   c:	66 90                	xchg   ax,ax
   e:	66 90                	xchg   ax,ax
  10:	53                   	push   rbx
  11:	55                   	push   rbp
  12:	56                   	push   rsi
  13:	57                   	push   rdi
  14:	41 50                	push   r8
  16:	41 51                	push   r9
  18:	48 81 ec 84 35 00 00 	sub    rsp,0x3584
  1f:	45 31 c0             	xor    r8d,r8d
  22:	4c 8d 0c 24          	lea    r9,[rsp]
  26:	48 b9 01 00 00 00 00 	movabs rcx,0x1
  2d:	00 00 00 
  30:	48 ba 02 00 00 00 00 	movabs rdx,0x2
  37:	00 00 00 
  3a:	48 b8 00 20 00 00 00 	movabs rax,0x2000
  41:	00 00 00 
  44:	48 83 eb 00          	sub    rbx,0x0
  48:	48 83 ed 00          	sub    rbp,0x0
  4c:	48 83 ee 00          	sub    rsi,0x0
  50:	48 83 ef 00          	sub    rdi,0x0
  54:	49 83 e8 00          	sub    r8,0x0
  58:	49 83 e9 00          	sub    r9,0x0
  5c:	49 83 ea 00          	sub    r10,0x0
  60:	49 83 eb 00          	sub    r11,0x0
  64:	49 83 ec 00          	sub    r12,0x0
  68:	49 83 ed 00          	sub    r13,0x0
  6c:	49 83 ee 00          	sub    r14,0x0
  70:	49 83 ef 00          	sub    r15,0x0
  74:	90                   	nop
  75:	90                   	nop
  76:	90                   	nop
  77:	90                   	nop
  78:	90                   	nop
  79:	90                   	nop
  7a:	90                   	nop
  7b:	90                   	nop
  7c:	90                   	nop
  7d:	90                   	nop
  7e:	90                   	nop
  7f:	90                   	nop
  80:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
  83:	8b dd                	mov    ebx,ebp
  85:	8b ee                	mov    ebp,esi
  87:	8b f7                	mov    esi,edi
  89:	8b fb                	mov    edi,ebx
  8b:	8b dd                	mov    ebx,ebp
  8d:	8b ee                	mov    ebp,esi
  8f:	8b f7                	mov    esi,edi
  91:	8b fb                	mov    edi,ebx
  93:	8b dd                	mov    ebx,ebp
  95:	8b ee                	mov    ebp,esi
  97:	8b f7                	mov    esi,edi
  99:	8b fb                	mov    edi,ebx
  9b:	8b dd                	mov    ebx,ebp
  9d:	8b ee                	mov    ebp,esi
  9f:	8b f7                	mov    esi,edi
  a1:	8b fb                	mov    edi,ebx
  a3:	8b dd                	mov    ebx,ebp
  a5:	8b ee                	mov    ebp,esi
  a7:	8b f7                	mov    esi,edi
  a9:	8b fb                	mov    edi,ebx
  ab:	8b dd                	mov    ebx,ebp
  ad:	8b ee                	mov    ebp,esi
  af:	8b f7                	mov    esi,edi
  b1:	8b fb                	mov    edi,ebx
  b3:	8b dd                	mov    ebx,ebp
  b5:	8b ee                	mov    ebp,esi
  b7:	8b f7                	mov    esi,edi
  b9:	8b fb                	mov    edi,ebx
  bb:	8b dd                	mov    ebx,ebp
  bd:	8b ee                	mov    ebp,esi
  bf:	8b f7                	mov    esi,edi
  c1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
  c4:	8b dd                	mov    ebx,ebp
  c6:	8b ee                	mov    ebp,esi
  c8:	8b f7                	mov    esi,edi
  ca:	8b fb                	mov    edi,ebx
  cc:	8b dd                	mov    ebx,ebp
  ce:	8b ee                	mov    ebp,esi
  d0:	8b f7                	mov    esi,edi
  d2:	8b fb                	mov    edi,ebx
  d4:	8b dd                	mov    ebx,ebp
  d6:	8b ee                	mov    ebp,esi
  d8:	8b f7                	mov    esi,edi
  da:	8b fb                	mov    edi,ebx
  dc:	8b dd                	mov    ebx,ebp
  de:	8b ee                	mov    ebp,esi
  e0:	8b f7                	mov    esi,edi
  e2:	8b fb                	mov    edi,ebx
  e4:	8b dd                	mov    ebx,ebp
  e6:	8b ee                	mov    ebp,esi
  e8:	8b f7                	mov    esi,edi
  ea:	8b fb                	mov    edi,ebx
  ec:	8b dd                	mov    ebx,ebp
  ee:	8b ee                	mov    ebp,esi
  f0:	8b f7                	mov    esi,edi
  f2:	8b fb                	mov    edi,ebx
  f4:	8b dd                	mov    ebx,ebp
  f6:	8b ee                	mov    ebp,esi
  f8:	8b f7                	mov    esi,edi
  fa:	8b fb                	mov    edi,ebx
  fc:	8b dd                	mov    ebx,ebp
  fe:	8b ee                	mov    ebp,esi
 100:	8b f7                	mov    esi,edi
 102:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 105:	8b dd                	mov    ebx,ebp
 107:	8b ee                	mov    ebp,esi
 109:	8b f7                	mov    esi,edi
 10b:	8b fb                	mov    edi,ebx
 10d:	8b dd                	mov    ebx,ebp
 10f:	8b ee                	mov    ebp,esi
 111:	8b f7                	mov    esi,edi
 113:	8b fb                	mov    edi,ebx
 115:	8b dd                	mov    ebx,ebp
 117:	8b ee                	mov    ebp,esi
 119:	8b f7                	mov    esi,edi
 11b:	8b fb                	mov    edi,ebx
 11d:	8b dd                	mov    ebx,ebp
 11f:	8b ee                	mov    ebp,esi
 121:	8b f7                	mov    esi,edi
 123:	8b fb                	mov    edi,ebx
 125:	8b dd                	mov    ebx,ebp
 127:	8b ee                	mov    ebp,esi
 129:	8b f7                	mov    esi,edi
 12b:	8b fb                	mov    edi,ebx
 12d:	8b dd                	mov    ebx,ebp
 12f:	8b ee                	mov    ebp,esi
 131:	8b f7                	mov    esi,edi
 133:	8b fb                	mov    edi,ebx
 135:	8b dd                	mov    ebx,ebp
 137:	8b ee                	mov    ebp,esi
 139:	8b f7                	mov    esi,edi
 13b:	8b fb                	mov    edi,ebx
 13d:	8b dd                	mov    ebx,ebp
 13f:	8b ee                	mov    ebp,esi
 141:	8b f7                	mov    esi,edi
 143:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 146:	8b dd                	mov    ebx,ebp
 148:	8b ee                	mov    ebp,esi
 14a:	8b f7                	mov    esi,edi
 14c:	8b fb                	mov    edi,ebx
 14e:	8b dd                	mov    ebx,ebp
 150:	8b ee                	mov    ebp,esi
 152:	8b f7                	mov    esi,edi
 154:	8b fb                	mov    edi,ebx
 156:	8b dd                	mov    ebx,ebp
 158:	8b ee                	mov    ebp,esi
 15a:	8b f7                	mov    esi,edi
 15c:	8b fb                	mov    edi,ebx
 15e:	8b dd                	mov    ebx,ebp
 160:	8b ee                	mov    ebp,esi
 162:	8b f7                	mov    esi,edi
 164:	8b fb                	mov    edi,ebx
 166:	8b dd                	mov    ebx,ebp
 168:	8b ee                	mov    ebp,esi
 16a:	8b f7                	mov    esi,edi
 16c:	8b fb                	mov    edi,ebx
 16e:	8b dd                	mov    ebx,ebp
 170:	8b ee                	mov    ebp,esi
 172:	8b f7                	mov    esi,edi
 174:	8b fb                	mov    edi,ebx
 176:	8b dd                	mov    ebx,ebp
 178:	8b ee                	mov    ebp,esi
 17a:	8b f7                	mov    esi,edi
 17c:	8b fb                	mov    edi,ebx
 17e:	8b dd                	mov    ebx,ebp
 180:	8b ee                	mov    ebp,esi
 182:	8b f7                	mov    esi,edi
 184:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 187:	8b dd                	mov    ebx,ebp
 189:	8b ee                	mov    ebp,esi
 18b:	8b f7                	mov    esi,edi
 18d:	8b fb                	mov    edi,ebx
 18f:	8b dd                	mov    ebx,ebp
 191:	8b ee                	mov    ebp,esi
 193:	8b f7                	mov    esi,edi
 195:	8b fb                	mov    edi,ebx
 197:	8b dd                	mov    ebx,ebp
 199:	8b ee                	mov    ebp,esi
 19b:	8b f7                	mov    esi,edi
 19d:	8b fb                	mov    edi,ebx
 19f:	8b dd                	mov    ebx,ebp
 1a1:	8b ee                	mov    ebp,esi
 1a3:	8b f7                	mov    esi,edi
 1a5:	8b fb                	mov    edi,ebx
 1a7:	8b dd                	mov    ebx,ebp
 1a9:	8b ee                	mov    ebp,esi
 1ab:	8b f7                	mov    esi,edi
 1ad:	8b fb                	mov    edi,ebx
 1af:	8b dd                	mov    ebx,ebp
 1b1:	8b ee                	mov    ebp,esi
 1b3:	8b f7                	mov    esi,edi
 1b5:	8b fb                	mov    edi,ebx
 1b7:	8b dd                	mov    ebx,ebp
 1b9:	8b ee                	mov    ebp,esi
 1bb:	8b f7                	mov    esi,edi
 1bd:	8b fb                	mov    edi,ebx
 1bf:	8b dd                	mov    ebx,ebp
 1c1:	8b ee                	mov    ebp,esi
 1c3:	8b f7                	mov    esi,edi
 1c5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 1c8:	8b dd                	mov    ebx,ebp
 1ca:	8b ee                	mov    ebp,esi
 1cc:	8b f7                	mov    esi,edi
 1ce:	8b fb                	mov    edi,ebx
 1d0:	8b dd                	mov    ebx,ebp
 1d2:	8b ee                	mov    ebp,esi
 1d4:	8b f7                	mov    esi,edi
 1d6:	8b fb                	mov    edi,ebx
 1d8:	8b dd                	mov    ebx,ebp
 1da:	8b ee                	mov    ebp,esi
 1dc:	8b f7                	mov    esi,edi
 1de:	8b fb                	mov    edi,ebx
 1e0:	8b dd                	mov    ebx,ebp
 1e2:	8b ee                	mov    ebp,esi
 1e4:	8b f7                	mov    esi,edi
 1e6:	8b fb                	mov    edi,ebx
 1e8:	8b dd                	mov    ebx,ebp
 1ea:	8b ee                	mov    ebp,esi
 1ec:	8b f7                	mov    esi,edi
 1ee:	8b fb                	mov    edi,ebx
 1f0:	8b dd                	mov    ebx,ebp
 1f2:	8b ee                	mov    ebp,esi
 1f4:	8b f7                	mov    esi,edi
 1f6:	8b fb                	mov    edi,ebx
 1f8:	8b dd                	mov    ebx,ebp
 1fa:	8b ee                	mov    ebp,esi
 1fc:	8b f7                	mov    esi,edi
 1fe:	8b fb                	mov    edi,ebx
 200:	8b dd                	mov    ebx,ebp
 202:	8b ee                	mov    ebp,esi
 204:	8b f7                	mov    esi,edi
 206:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 209:	8b dd                	mov    ebx,ebp
 20b:	8b ee                	mov    ebp,esi
 20d:	8b f7                	mov    esi,edi
 20f:	8b fb                	mov    edi,ebx
 211:	8b dd                	mov    ebx,ebp
 213:	8b ee                	mov    ebp,esi
 215:	8b f7                	mov    esi,edi
 217:	8b fb                	mov    edi,ebx
 219:	8b dd                	mov    ebx,ebp
 21b:	8b ee                	mov    ebp,esi
 21d:	8b f7                	mov    esi,edi
 21f:	8b fb                	mov    edi,ebx
 221:	8b dd                	mov    ebx,ebp
 223:	8b ee                	mov    ebp,esi
 225:	8b f7                	mov    esi,edi
 227:	8b fb                	mov    edi,ebx
 229:	8b dd                	mov    ebx,ebp
 22b:	8b ee                	mov    ebp,esi
 22d:	8b f7                	mov    esi,edi
 22f:	8b fb                	mov    edi,ebx
 231:	8b dd                	mov    ebx,ebp
 233:	8b ee                	mov    ebp,esi
 235:	8b f7                	mov    esi,edi
 237:	8b fb                	mov    edi,ebx
 239:	8b dd                	mov    ebx,ebp
 23b:	8b ee                	mov    ebp,esi
 23d:	8b f7                	mov    esi,edi
 23f:	8b fb                	mov    edi,ebx
 241:	8b dd                	mov    ebx,ebp
 243:	8b ee                	mov    ebp,esi
 245:	8b f7                	mov    esi,edi
 247:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 24a:	8b dd                	mov    ebx,ebp
 24c:	8b ee                	mov    ebp,esi
 24e:	8b f7                	mov    esi,edi
 250:	8b fb                	mov    edi,ebx
 252:	8b dd                	mov    ebx,ebp
 254:	8b ee                	mov    ebp,esi
 256:	8b f7                	mov    esi,edi
 258:	8b fb                	mov    edi,ebx
 25a:	8b dd                	mov    ebx,ebp
 25c:	8b ee                	mov    ebp,esi
 25e:	8b f7                	mov    esi,edi
 260:	8b fb                	mov    edi,ebx
 262:	8b dd                	mov    ebx,ebp
 264:	8b ee                	mov    ebp,esi
 266:	8b f7                	mov    esi,edi
 268:	8b fb                	mov    edi,ebx
 26a:	8b dd                	mov    ebx,ebp
 26c:	8b ee                	mov    ebp,esi
 26e:	8b f7                	mov    esi,edi
 270:	8b fb                	mov    edi,ebx
 272:	8b dd                	mov    ebx,ebp
 274:	8b ee                	mov    ebp,esi
 276:	8b f7                	mov    esi,edi
 278:	8b fb                	mov    edi,ebx
 27a:	8b dd                	mov    ebx,ebp
 27c:	8b ee                	mov    ebp,esi
 27e:	8b f7                	mov    esi,edi
 280:	8b fb                	mov    edi,ebx
 282:	8b dd                	mov    ebx,ebp
 284:	8b ee                	mov    ebp,esi
 286:	8b f7                	mov    esi,edi
 288:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 28b:	8b dd                	mov    ebx,ebp
 28d:	8b ee                	mov    ebp,esi
 28f:	8b f7                	mov    esi,edi
 291:	8b fb                	mov    edi,ebx
 293:	8b dd                	mov    ebx,ebp
 295:	8b ee                	mov    ebp,esi
 297:	8b f7                	mov    esi,edi
 299:	8b fb                	mov    edi,ebx
 29b:	8b dd                	mov    ebx,ebp
 29d:	8b ee                	mov    ebp,esi
 29f:	8b f7                	mov    esi,edi
 2a1:	8b fb                	mov    edi,ebx
 2a3:	8b dd                	mov    ebx,ebp
 2a5:	8b ee                	mov    ebp,esi
 2a7:	8b f7                	mov    esi,edi
 2a9:	8b fb                	mov    edi,ebx
 2ab:	8b dd                	mov    ebx,ebp
 2ad:	8b ee                	mov    ebp,esi
 2af:	8b f7                	mov    esi,edi
 2b1:	8b fb                	mov    edi,ebx
 2b3:	8b dd                	mov    ebx,ebp
 2b5:	8b ee                	mov    ebp,esi
 2b7:	8b f7                	mov    esi,edi
 2b9:	8b fb                	mov    edi,ebx
 2bb:	8b dd                	mov    ebx,ebp
 2bd:	8b ee                	mov    ebp,esi
 2bf:	8b f7                	mov    esi,edi
 2c1:	8b fb                	mov    edi,ebx
 2c3:	8b dd                	mov    ebx,ebp
 2c5:	8b ee                	mov    ebp,esi
 2c7:	8b f7                	mov    esi,edi
 2c9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 2cc:	8b dd                	mov    ebx,ebp
 2ce:	8b ee                	mov    ebp,esi
 2d0:	8b f7                	mov    esi,edi
 2d2:	8b fb                	mov    edi,ebx
 2d4:	8b dd                	mov    ebx,ebp
 2d6:	8b ee                	mov    ebp,esi
 2d8:	8b f7                	mov    esi,edi
 2da:	8b fb                	mov    edi,ebx
 2dc:	8b dd                	mov    ebx,ebp
 2de:	8b ee                	mov    ebp,esi
 2e0:	8b f7                	mov    esi,edi
 2e2:	8b fb                	mov    edi,ebx
 2e4:	8b dd                	mov    ebx,ebp
 2e6:	8b ee                	mov    ebp,esi
 2e8:	8b f7                	mov    esi,edi
 2ea:	8b fb                	mov    edi,ebx
 2ec:	8b dd                	mov    ebx,ebp
 2ee:	8b ee                	mov    ebp,esi
 2f0:	8b f7                	mov    esi,edi
 2f2:	8b fb                	mov    edi,ebx
 2f4:	8b dd                	mov    ebx,ebp
 2f6:	8b ee                	mov    ebp,esi
 2f8:	8b f7                	mov    esi,edi
 2fa:	8b fb                	mov    edi,ebx
 2fc:	8b dd                	mov    ebx,ebp
 2fe:	8b ee                	mov    ebp,esi
 300:	8b f7                	mov    esi,edi
 302:	8b fb                	mov    edi,ebx
 304:	8b dd                	mov    ebx,ebp
 306:	8b ee                	mov    ebp,esi
 308:	8b f7                	mov    esi,edi
 30a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 30d:	8b dd                	mov    ebx,ebp
 30f:	8b ee                	mov    ebp,esi
 311:	8b f7                	mov    esi,edi
 313:	8b fb                	mov    edi,ebx
 315:	8b dd                	mov    ebx,ebp
 317:	8b ee                	mov    ebp,esi
 319:	8b f7                	mov    esi,edi
 31b:	8b fb                	mov    edi,ebx
 31d:	8b dd                	mov    ebx,ebp
 31f:	8b ee                	mov    ebp,esi
 321:	8b f7                	mov    esi,edi
 323:	8b fb                	mov    edi,ebx
 325:	8b dd                	mov    ebx,ebp
 327:	8b ee                	mov    ebp,esi
 329:	8b f7                	mov    esi,edi
 32b:	8b fb                	mov    edi,ebx
 32d:	8b dd                	mov    ebx,ebp
 32f:	8b ee                	mov    ebp,esi
 331:	8b f7                	mov    esi,edi
 333:	8b fb                	mov    edi,ebx
 335:	8b dd                	mov    ebx,ebp
 337:	8b ee                	mov    ebp,esi
 339:	8b f7                	mov    esi,edi
 33b:	8b fb                	mov    edi,ebx
 33d:	8b dd                	mov    ebx,ebp
 33f:	8b ee                	mov    ebp,esi
 341:	8b f7                	mov    esi,edi
 343:	8b fb                	mov    edi,ebx
 345:	8b dd                	mov    ebx,ebp
 347:	8b ee                	mov    ebp,esi
 349:	8b f7                	mov    esi,edi
 34b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 34e:	8b dd                	mov    ebx,ebp
 350:	8b ee                	mov    ebp,esi
 352:	8b f7                	mov    esi,edi
 354:	8b fb                	mov    edi,ebx
 356:	8b dd                	mov    ebx,ebp
 358:	8b ee                	mov    ebp,esi
 35a:	8b f7                	mov    esi,edi
 35c:	8b fb                	mov    edi,ebx
 35e:	8b dd                	mov    ebx,ebp
 360:	8b ee                	mov    ebp,esi
 362:	8b f7                	mov    esi,edi
 364:	8b fb                	mov    edi,ebx
 366:	8b dd                	mov    ebx,ebp
 368:	8b ee                	mov    ebp,esi
 36a:	8b f7                	mov    esi,edi
 36c:	8b fb                	mov    edi,ebx
 36e:	8b dd                	mov    ebx,ebp
 370:	8b ee                	mov    ebp,esi
 372:	8b f7                	mov    esi,edi
 374:	8b fb                	mov    edi,ebx
 376:	8b dd                	mov    ebx,ebp
 378:	8b ee                	mov    ebp,esi
 37a:	8b f7                	mov    esi,edi
 37c:	8b fb                	mov    edi,ebx
 37e:	8b dd                	mov    ebx,ebp
 380:	8b ee                	mov    ebp,esi
 382:	8b f7                	mov    esi,edi
 384:	8b fb                	mov    edi,ebx
 386:	8b dd                	mov    ebx,ebp
 388:	8b ee                	mov    ebp,esi
 38a:	8b f7                	mov    esi,edi
 38c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 38f:	8b dd                	mov    ebx,ebp
 391:	8b ee                	mov    ebp,esi
 393:	8b f7                	mov    esi,edi
 395:	8b fb                	mov    edi,ebx
 397:	8b dd                	mov    ebx,ebp
 399:	8b ee                	mov    ebp,esi
 39b:	8b f7                	mov    esi,edi
 39d:	8b fb                	mov    edi,ebx
 39f:	8b dd                	mov    ebx,ebp
 3a1:	8b ee                	mov    ebp,esi
 3a3:	8b f7                	mov    esi,edi
 3a5:	8b fb                	mov    edi,ebx
 3a7:	8b dd                	mov    ebx,ebp
 3a9:	8b ee                	mov    ebp,esi
 3ab:	8b f7                	mov    esi,edi
 3ad:	8b fb                	mov    edi,ebx
 3af:	8b dd                	mov    ebx,ebp
 3b1:	8b ee                	mov    ebp,esi
 3b3:	8b f7                	mov    esi,edi
 3b5:	8b fb                	mov    edi,ebx
 3b7:	8b dd                	mov    ebx,ebp
 3b9:	8b ee                	mov    ebp,esi
 3bb:	8b f7                	mov    esi,edi
 3bd:	8b fb                	mov    edi,ebx
 3bf:	8b dd                	mov    ebx,ebp
 3c1:	8b ee                	mov    ebp,esi
 3c3:	8b f7                	mov    esi,edi
 3c5:	8b fb                	mov    edi,ebx
 3c7:	8b dd                	mov    ebx,ebp
 3c9:	8b ee                	mov    ebp,esi
 3cb:	8b f7                	mov    esi,edi
 3cd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 3d0:	8b dd                	mov    ebx,ebp
 3d2:	8b ee                	mov    ebp,esi
 3d4:	8b f7                	mov    esi,edi
 3d6:	8b fb                	mov    edi,ebx
 3d8:	8b dd                	mov    ebx,ebp
 3da:	8b ee                	mov    ebp,esi
 3dc:	8b f7                	mov    esi,edi
 3de:	8b fb                	mov    edi,ebx
 3e0:	8b dd                	mov    ebx,ebp
 3e2:	8b ee                	mov    ebp,esi
 3e4:	8b f7                	mov    esi,edi
 3e6:	8b fb                	mov    edi,ebx
 3e8:	8b dd                	mov    ebx,ebp
 3ea:	8b ee                	mov    ebp,esi
 3ec:	8b f7                	mov    esi,edi
 3ee:	8b fb                	mov    edi,ebx
 3f0:	8b dd                	mov    ebx,ebp
 3f2:	8b ee                	mov    ebp,esi
 3f4:	8b f7                	mov    esi,edi
 3f6:	8b fb                	mov    edi,ebx
 3f8:	8b dd                	mov    ebx,ebp
 3fa:	8b ee                	mov    ebp,esi
 3fc:	8b f7                	mov    esi,edi
 3fe:	8b fb                	mov    edi,ebx
 400:	8b dd                	mov    ebx,ebp
 402:	8b ee                	mov    ebp,esi
 404:	8b f7                	mov    esi,edi
 406:	8b fb                	mov    edi,ebx
 408:	8b dd                	mov    ebx,ebp
 40a:	8b ee                	mov    ebp,esi
 40c:	8b f7                	mov    esi,edi
 40e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 411:	8b dd                	mov    ebx,ebp
 413:	8b ee                	mov    ebp,esi
 415:	8b f7                	mov    esi,edi
 417:	8b fb                	mov    edi,ebx
 419:	8b dd                	mov    ebx,ebp
 41b:	8b ee                	mov    ebp,esi
 41d:	8b f7                	mov    esi,edi
 41f:	8b fb                	mov    edi,ebx
 421:	8b dd                	mov    ebx,ebp
 423:	8b ee                	mov    ebp,esi
 425:	8b f7                	mov    esi,edi
 427:	8b fb                	mov    edi,ebx
 429:	8b dd                	mov    ebx,ebp
 42b:	8b ee                	mov    ebp,esi
 42d:	8b f7                	mov    esi,edi
 42f:	8b fb                	mov    edi,ebx
 431:	8b dd                	mov    ebx,ebp
 433:	8b ee                	mov    ebp,esi
 435:	8b f7                	mov    esi,edi
 437:	8b fb                	mov    edi,ebx
 439:	8b dd                	mov    ebx,ebp
 43b:	8b ee                	mov    ebp,esi
 43d:	8b f7                	mov    esi,edi
 43f:	8b fb                	mov    edi,ebx
 441:	8b dd                	mov    ebx,ebp
 443:	8b ee                	mov    ebp,esi
 445:	8b f7                	mov    esi,edi
 447:	8b fb                	mov    edi,ebx
 449:	8b dd                	mov    ebx,ebp
 44b:	8b ee                	mov    ebp,esi
 44d:	8b f7                	mov    esi,edi
 44f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 452:	8b dd                	mov    ebx,ebp
 454:	8b ee                	mov    ebp,esi
 456:	8b f7                	mov    esi,edi
 458:	8b fb                	mov    edi,ebx
 45a:	8b dd                	mov    ebx,ebp
 45c:	8b ee                	mov    ebp,esi
 45e:	8b f7                	mov    esi,edi
 460:	8b fb                	mov    edi,ebx
 462:	8b dd                	mov    ebx,ebp
 464:	8b ee                	mov    ebp,esi
 466:	8b f7                	mov    esi,edi
 468:	8b fb                	mov    edi,ebx
 46a:	8b dd                	mov    ebx,ebp
 46c:	8b ee                	mov    ebp,esi
 46e:	8b f7                	mov    esi,edi
 470:	8b fb                	mov    edi,ebx
 472:	8b dd                	mov    ebx,ebp
 474:	8b ee                	mov    ebp,esi
 476:	8b f7                	mov    esi,edi
 478:	8b fb                	mov    edi,ebx
 47a:	8b dd                	mov    ebx,ebp
 47c:	8b ee                	mov    ebp,esi
 47e:	8b f7                	mov    esi,edi
 480:	8b fb                	mov    edi,ebx
 482:	8b dd                	mov    ebx,ebp
 484:	8b ee                	mov    ebp,esi
 486:	8b f7                	mov    esi,edi
 488:	8b fb                	mov    edi,ebx
 48a:	8b dd                	mov    ebx,ebp
 48c:	8b ee                	mov    ebp,esi
 48e:	8b f7                	mov    esi,edi
 490:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 493:	8b dd                	mov    ebx,ebp
 495:	8b ee                	mov    ebp,esi
 497:	8b f7                	mov    esi,edi
 499:	8b fb                	mov    edi,ebx
 49b:	8b dd                	mov    ebx,ebp
 49d:	8b ee                	mov    ebp,esi
 49f:	8b f7                	mov    esi,edi
 4a1:	8b fb                	mov    edi,ebx
 4a3:	8b dd                	mov    ebx,ebp
 4a5:	8b ee                	mov    ebp,esi
 4a7:	8b f7                	mov    esi,edi
 4a9:	8b fb                	mov    edi,ebx
 4ab:	8b dd                	mov    ebx,ebp
 4ad:	8b ee                	mov    ebp,esi
 4af:	8b f7                	mov    esi,edi
 4b1:	8b fb                	mov    edi,ebx
 4b3:	8b dd                	mov    ebx,ebp
 4b5:	8b ee                	mov    ebp,esi
 4b7:	8b f7                	mov    esi,edi
 4b9:	8b fb                	mov    edi,ebx
 4bb:	8b dd                	mov    ebx,ebp
 4bd:	8b ee                	mov    ebp,esi
 4bf:	8b f7                	mov    esi,edi
 4c1:	8b fb                	mov    edi,ebx
 4c3:	8b dd                	mov    ebx,ebp
 4c5:	8b ee                	mov    ebp,esi
 4c7:	8b f7                	mov    esi,edi
 4c9:	8b fb                	mov    edi,ebx
 4cb:	8b dd                	mov    ebx,ebp
 4cd:	8b ee                	mov    ebp,esi
 4cf:	8b f7                	mov    esi,edi
 4d1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 4d4:	8b dd                	mov    ebx,ebp
 4d6:	8b ee                	mov    ebp,esi
 4d8:	8b f7                	mov    esi,edi
 4da:	8b fb                	mov    edi,ebx
 4dc:	8b dd                	mov    ebx,ebp
 4de:	8b ee                	mov    ebp,esi
 4e0:	8b f7                	mov    esi,edi
 4e2:	8b fb                	mov    edi,ebx
 4e4:	8b dd                	mov    ebx,ebp
 4e6:	8b ee                	mov    ebp,esi
 4e8:	8b f7                	mov    esi,edi
 4ea:	8b fb                	mov    edi,ebx
 4ec:	8b dd                	mov    ebx,ebp
 4ee:	8b ee                	mov    ebp,esi
 4f0:	8b f7                	mov    esi,edi
 4f2:	8b fb                	mov    edi,ebx
 4f4:	8b dd                	mov    ebx,ebp
 4f6:	8b ee                	mov    ebp,esi
 4f8:	8b f7                	mov    esi,edi
 4fa:	8b fb                	mov    edi,ebx
 4fc:	8b dd                	mov    ebx,ebp
 4fe:	8b ee                	mov    ebp,esi
 500:	8b f7                	mov    esi,edi
 502:	8b fb                	mov    edi,ebx
 504:	8b dd                	mov    ebx,ebp
 506:	8b ee                	mov    ebp,esi
 508:	8b f7                	mov    esi,edi
 50a:	8b fb                	mov    edi,ebx
 50c:	8b dd                	mov    ebx,ebp
 50e:	8b ee                	mov    ebp,esi
 510:	8b f7                	mov    esi,edi
 512:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 515:	8b dd                	mov    ebx,ebp
 517:	8b ee                	mov    ebp,esi
 519:	8b f7                	mov    esi,edi
 51b:	8b fb                	mov    edi,ebx
 51d:	8b dd                	mov    ebx,ebp
 51f:	8b ee                	mov    ebp,esi
 521:	8b f7                	mov    esi,edi
 523:	8b fb                	mov    edi,ebx
 525:	8b dd                	mov    ebx,ebp
 527:	8b ee                	mov    ebp,esi
 529:	8b f7                	mov    esi,edi
 52b:	8b fb                	mov    edi,ebx
 52d:	8b dd                	mov    ebx,ebp
 52f:	8b ee                	mov    ebp,esi
 531:	8b f7                	mov    esi,edi
 533:	8b fb                	mov    edi,ebx
 535:	8b dd                	mov    ebx,ebp
 537:	8b ee                	mov    ebp,esi
 539:	8b f7                	mov    esi,edi
 53b:	8b fb                	mov    edi,ebx
 53d:	8b dd                	mov    ebx,ebp
 53f:	8b ee                	mov    ebp,esi
 541:	8b f7                	mov    esi,edi
 543:	8b fb                	mov    edi,ebx
 545:	8b dd                	mov    ebx,ebp
 547:	8b ee                	mov    ebp,esi
 549:	8b f7                	mov    esi,edi
 54b:	8b fb                	mov    edi,ebx
 54d:	8b dd                	mov    ebx,ebp
 54f:	8b ee                	mov    ebp,esi
 551:	8b f7                	mov    esi,edi
 553:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 556:	8b dd                	mov    ebx,ebp
 558:	8b ee                	mov    ebp,esi
 55a:	8b f7                	mov    esi,edi
 55c:	8b fb                	mov    edi,ebx
 55e:	8b dd                	mov    ebx,ebp
 560:	8b ee                	mov    ebp,esi
 562:	8b f7                	mov    esi,edi
 564:	8b fb                	mov    edi,ebx
 566:	8b dd                	mov    ebx,ebp
 568:	8b ee                	mov    ebp,esi
 56a:	8b f7                	mov    esi,edi
 56c:	8b fb                	mov    edi,ebx
 56e:	8b dd                	mov    ebx,ebp
 570:	8b ee                	mov    ebp,esi
 572:	8b f7                	mov    esi,edi
 574:	8b fb                	mov    edi,ebx
 576:	8b dd                	mov    ebx,ebp
 578:	8b ee                	mov    ebp,esi
 57a:	8b f7                	mov    esi,edi
 57c:	8b fb                	mov    edi,ebx
 57e:	8b dd                	mov    ebx,ebp
 580:	8b ee                	mov    ebp,esi
 582:	8b f7                	mov    esi,edi
 584:	8b fb                	mov    edi,ebx
 586:	8b dd                	mov    ebx,ebp
 588:	8b ee                	mov    ebp,esi
 58a:	8b f7                	mov    esi,edi
 58c:	8b fb                	mov    edi,ebx
 58e:	8b dd                	mov    ebx,ebp
 590:	8b ee                	mov    ebp,esi
 592:	8b f7                	mov    esi,edi
 594:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 597:	8b dd                	mov    ebx,ebp
 599:	8b ee                	mov    ebp,esi
 59b:	8b f7                	mov    esi,edi
 59d:	8b fb                	mov    edi,ebx
 59f:	8b dd                	mov    ebx,ebp
 5a1:	8b ee                	mov    ebp,esi
 5a3:	8b f7                	mov    esi,edi
 5a5:	8b fb                	mov    edi,ebx
 5a7:	8b dd                	mov    ebx,ebp
 5a9:	8b ee                	mov    ebp,esi
 5ab:	8b f7                	mov    esi,edi
 5ad:	8b fb                	mov    edi,ebx
 5af:	8b dd                	mov    ebx,ebp
 5b1:	8b ee                	mov    ebp,esi
 5b3:	8b f7                	mov    esi,edi
 5b5:	8b fb                	mov    edi,ebx
 5b7:	8b dd                	mov    ebx,ebp
 5b9:	8b ee                	mov    ebp,esi
 5bb:	8b f7                	mov    esi,edi
 5bd:	8b fb                	mov    edi,ebx
 5bf:	8b dd                	mov    ebx,ebp
 5c1:	8b ee                	mov    ebp,esi
 5c3:	8b f7                	mov    esi,edi
 5c5:	8b fb                	mov    edi,ebx
 5c7:	8b dd                	mov    ebx,ebp
 5c9:	8b ee                	mov    ebp,esi
 5cb:	8b f7                	mov    esi,edi
 5cd:	8b fb                	mov    edi,ebx
 5cf:	8b dd                	mov    ebx,ebp
 5d1:	8b ee                	mov    ebp,esi
 5d3:	8b f7                	mov    esi,edi
 5d5:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 5d8:	8b dd                	mov    ebx,ebp
 5da:	8b ee                	mov    ebp,esi
 5dc:	8b f7                	mov    esi,edi
 5de:	8b fb                	mov    edi,ebx
 5e0:	8b dd                	mov    ebx,ebp
 5e2:	8b ee                	mov    ebp,esi
 5e4:	8b f7                	mov    esi,edi
 5e6:	8b fb                	mov    edi,ebx
 5e8:	8b dd                	mov    ebx,ebp
 5ea:	8b ee                	mov    ebp,esi
 5ec:	8b f7                	mov    esi,edi
 5ee:	8b fb                	mov    edi,ebx
 5f0:	8b dd                	mov    ebx,ebp
 5f2:	8b ee                	mov    ebp,esi
 5f4:	8b f7                	mov    esi,edi
 5f6:	8b fb                	mov    edi,ebx
 5f8:	8b dd                	mov    ebx,ebp
 5fa:	8b ee                	mov    ebp,esi
 5fc:	8b f7                	mov    esi,edi
 5fe:	8b fb                	mov    edi,ebx
 600:	8b dd                	mov    ebx,ebp
 602:	8b ee                	mov    ebp,esi
 604:	8b f7                	mov    esi,edi
 606:	8b fb                	mov    edi,ebx
 608:	8b dd                	mov    ebx,ebp
 60a:	8b ee                	mov    ebp,esi
 60c:	8b f7                	mov    esi,edi
 60e:	8b fb                	mov    edi,ebx
 610:	8b dd                	mov    ebx,ebp
 612:	8b ee                	mov    ebp,esi
 614:	8b f7                	mov    esi,edi
 616:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 619:	8b dd                	mov    ebx,ebp
 61b:	8b ee                	mov    ebp,esi
 61d:	8b f7                	mov    esi,edi
 61f:	8b fb                	mov    edi,ebx
 621:	8b dd                	mov    ebx,ebp
 623:	8b ee                	mov    ebp,esi
 625:	8b f7                	mov    esi,edi
 627:	8b fb                	mov    edi,ebx
 629:	8b dd                	mov    ebx,ebp
 62b:	8b ee                	mov    ebp,esi
 62d:	8b f7                	mov    esi,edi
 62f:	8b fb                	mov    edi,ebx
 631:	8b dd                	mov    ebx,ebp
 633:	8b ee                	mov    ebp,esi
 635:	8b f7                	mov    esi,edi
 637:	8b fb                	mov    edi,ebx
 639:	8b dd                	mov    ebx,ebp
 63b:	8b ee                	mov    ebp,esi
 63d:	8b f7                	mov    esi,edi
 63f:	8b fb                	mov    edi,ebx
 641:	8b dd                	mov    ebx,ebp
 643:	8b ee                	mov    ebp,esi
 645:	8b f7                	mov    esi,edi
 647:	8b fb                	mov    edi,ebx
 649:	8b dd                	mov    ebx,ebp
 64b:	8b ee                	mov    ebp,esi
 64d:	8b f7                	mov    esi,edi
 64f:	8b fb                	mov    edi,ebx
 651:	8b dd                	mov    ebx,ebp
 653:	8b ee                	mov    ebp,esi
 655:	8b f7                	mov    esi,edi
 657:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 65a:	8b dd                	mov    ebx,ebp
 65c:	8b ee                	mov    ebp,esi
 65e:	8b f7                	mov    esi,edi
 660:	8b fb                	mov    edi,ebx
 662:	8b dd                	mov    ebx,ebp
 664:	8b ee                	mov    ebp,esi
 666:	8b f7                	mov    esi,edi
 668:	8b fb                	mov    edi,ebx
 66a:	8b dd                	mov    ebx,ebp
 66c:	8b ee                	mov    ebp,esi
 66e:	8b f7                	mov    esi,edi
 670:	8b fb                	mov    edi,ebx
 672:	8b dd                	mov    ebx,ebp
 674:	8b ee                	mov    ebp,esi
 676:	8b f7                	mov    esi,edi
 678:	8b fb                	mov    edi,ebx
 67a:	8b dd                	mov    ebx,ebp
 67c:	8b ee                	mov    ebp,esi
 67e:	8b f7                	mov    esi,edi
 680:	8b fb                	mov    edi,ebx
 682:	8b dd                	mov    ebx,ebp
 684:	8b ee                	mov    ebp,esi
 686:	8b f7                	mov    esi,edi
 688:	8b fb                	mov    edi,ebx
 68a:	8b dd                	mov    ebx,ebp
 68c:	8b ee                	mov    ebp,esi
 68e:	8b f7                	mov    esi,edi
 690:	8b fb                	mov    edi,ebx
 692:	8b dd                	mov    ebx,ebp
 694:	8b ee                	mov    ebp,esi
 696:	8b f7                	mov    esi,edi
 698:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 69b:	8b dd                	mov    ebx,ebp
 69d:	8b ee                	mov    ebp,esi
 69f:	8b f7                	mov    esi,edi
 6a1:	8b fb                	mov    edi,ebx
 6a3:	8b dd                	mov    ebx,ebp
 6a5:	8b ee                	mov    ebp,esi
 6a7:	8b f7                	mov    esi,edi
 6a9:	8b fb                	mov    edi,ebx
 6ab:	8b dd                	mov    ebx,ebp
 6ad:	8b ee                	mov    ebp,esi
 6af:	8b f7                	mov    esi,edi
 6b1:	8b fb                	mov    edi,ebx
 6b3:	8b dd                	mov    ebx,ebp
 6b5:	8b ee                	mov    ebp,esi
 6b7:	8b f7                	mov    esi,edi
 6b9:	8b fb                	mov    edi,ebx
 6bb:	8b dd                	mov    ebx,ebp
 6bd:	8b ee                	mov    ebp,esi
 6bf:	8b f7                	mov    esi,edi
 6c1:	8b fb                	mov    edi,ebx
 6c3:	8b dd                	mov    ebx,ebp
 6c5:	8b ee                	mov    ebp,esi
 6c7:	8b f7                	mov    esi,edi
 6c9:	8b fb                	mov    edi,ebx
 6cb:	8b dd                	mov    ebx,ebp
 6cd:	8b ee                	mov    ebp,esi
 6cf:	8b f7                	mov    esi,edi
 6d1:	8b fb                	mov    edi,ebx
 6d3:	8b dd                	mov    ebx,ebp
 6d5:	8b ee                	mov    ebp,esi
 6d7:	8b f7                	mov    esi,edi
 6d9:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 6dc:	8b dd                	mov    ebx,ebp
 6de:	8b ee                	mov    ebp,esi
 6e0:	8b f7                	mov    esi,edi
 6e2:	8b fb                	mov    edi,ebx
 6e4:	8b dd                	mov    ebx,ebp
 6e6:	8b ee                	mov    ebp,esi
 6e8:	8b f7                	mov    esi,edi
 6ea:	8b fb                	mov    edi,ebx
 6ec:	8b dd                	mov    ebx,ebp
 6ee:	8b ee                	mov    ebp,esi
 6f0:	8b f7                	mov    esi,edi
 6f2:	8b fb                	mov    edi,ebx
 6f4:	8b dd                	mov    ebx,ebp
 6f6:	8b ee                	mov    ebp,esi
 6f8:	8b f7                	mov    esi,edi
 6fa:	8b fb                	mov    edi,ebx
 6fc:	8b dd                	mov    ebx,ebp
 6fe:	8b ee                	mov    ebp,esi
 700:	8b f7                	mov    esi,edi
 702:	8b fb                	mov    edi,ebx
 704:	8b dd                	mov    ebx,ebp
 706:	8b ee                	mov    ebp,esi
 708:	8b f7                	mov    esi,edi
 70a:	8b fb                	mov    edi,ebx
 70c:	8b dd                	mov    ebx,ebp
 70e:	8b ee                	mov    ebp,esi
 710:	8b f7                	mov    esi,edi
 712:	8b fb                	mov    edi,ebx
 714:	8b dd                	mov    ebx,ebp
 716:	8b ee                	mov    ebp,esi
 718:	8b f7                	mov    esi,edi
 71a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 71d:	8b dd                	mov    ebx,ebp
 71f:	8b ee                	mov    ebp,esi
 721:	8b f7                	mov    esi,edi
 723:	8b fb                	mov    edi,ebx
 725:	8b dd                	mov    ebx,ebp
 727:	8b ee                	mov    ebp,esi
 729:	8b f7                	mov    esi,edi
 72b:	8b fb                	mov    edi,ebx
 72d:	8b dd                	mov    ebx,ebp
 72f:	8b ee                	mov    ebp,esi
 731:	8b f7                	mov    esi,edi
 733:	8b fb                	mov    edi,ebx
 735:	8b dd                	mov    ebx,ebp
 737:	8b ee                	mov    ebp,esi
 739:	8b f7                	mov    esi,edi
 73b:	8b fb                	mov    edi,ebx
 73d:	8b dd                	mov    ebx,ebp
 73f:	8b ee                	mov    ebp,esi
 741:	8b f7                	mov    esi,edi
 743:	8b fb                	mov    edi,ebx
 745:	8b dd                	mov    ebx,ebp
 747:	8b ee                	mov    ebp,esi
 749:	8b f7                	mov    esi,edi
 74b:	8b fb                	mov    edi,ebx
 74d:	8b dd                	mov    ebx,ebp
 74f:	8b ee                	mov    ebp,esi
 751:	8b f7                	mov    esi,edi
 753:	8b fb                	mov    edi,ebx
 755:	8b dd                	mov    ebx,ebp
 757:	8b ee                	mov    ebp,esi
 759:	8b f7                	mov    esi,edi
 75b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 75e:	8b dd                	mov    ebx,ebp
 760:	8b ee                	mov    ebp,esi
 762:	8b f7                	mov    esi,edi
 764:	8b fb                	mov    edi,ebx
 766:	8b dd                	mov    ebx,ebp
 768:	8b ee                	mov    ebp,esi
 76a:	8b f7                	mov    esi,edi
 76c:	8b fb                	mov    edi,ebx
 76e:	8b dd                	mov    ebx,ebp
 770:	8b ee                	mov    ebp,esi
 772:	8b f7                	mov    esi,edi
 774:	8b fb                	mov    edi,ebx
 776:	8b dd                	mov    ebx,ebp
 778:	8b ee                	mov    ebp,esi
 77a:	8b f7                	mov    esi,edi
 77c:	8b fb                	mov    edi,ebx
 77e:	8b dd                	mov    ebx,ebp
 780:	8b ee                	mov    ebp,esi
 782:	8b f7                	mov    esi,edi
 784:	8b fb                	mov    edi,ebx
 786:	8b dd                	mov    ebx,ebp
 788:	8b ee                	mov    ebp,esi
 78a:	8b f7                	mov    esi,edi
 78c:	8b fb                	mov    edi,ebx
 78e:	8b dd                	mov    ebx,ebp
 790:	8b ee                	mov    ebp,esi
 792:	8b f7                	mov    esi,edi
 794:	8b fb                	mov    edi,ebx
 796:	8b dd                	mov    ebx,ebp
 798:	8b ee                	mov    ebp,esi
 79a:	8b f7                	mov    esi,edi
 79c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 79f:	8b dd                	mov    ebx,ebp
 7a1:	8b ee                	mov    ebp,esi
 7a3:	8b f7                	mov    esi,edi
 7a5:	8b fb                	mov    edi,ebx
 7a7:	8b dd                	mov    ebx,ebp
 7a9:	8b ee                	mov    ebp,esi
 7ab:	8b f7                	mov    esi,edi
 7ad:	8b fb                	mov    edi,ebx
 7af:	8b dd                	mov    ebx,ebp
 7b1:	8b ee                	mov    ebp,esi
 7b3:	8b f7                	mov    esi,edi
 7b5:	8b fb                	mov    edi,ebx
 7b7:	8b dd                	mov    ebx,ebp
 7b9:	8b ee                	mov    ebp,esi
 7bb:	8b f7                	mov    esi,edi
 7bd:	8b fb                	mov    edi,ebx
 7bf:	8b dd                	mov    ebx,ebp
 7c1:	8b ee                	mov    ebp,esi
 7c3:	8b f7                	mov    esi,edi
 7c5:	8b fb                	mov    edi,ebx
 7c7:	8b dd                	mov    ebx,ebp
 7c9:	8b ee                	mov    ebp,esi
 7cb:	8b f7                	mov    esi,edi
 7cd:	8b fb                	mov    edi,ebx
 7cf:	8b dd                	mov    ebx,ebp
 7d1:	8b ee                	mov    ebp,esi
 7d3:	8b f7                	mov    esi,edi
 7d5:	8b fb                	mov    edi,ebx
 7d7:	8b dd                	mov    ebx,ebp
 7d9:	8b ee                	mov    ebp,esi
 7db:	8b f7                	mov    esi,edi
 7dd:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 7e0:	8b dd                	mov    ebx,ebp
 7e2:	8b ee                	mov    ebp,esi
 7e4:	8b f7                	mov    esi,edi
 7e6:	8b fb                	mov    edi,ebx
 7e8:	8b dd                	mov    ebx,ebp
 7ea:	8b ee                	mov    ebp,esi
 7ec:	8b f7                	mov    esi,edi
 7ee:	8b fb                	mov    edi,ebx
 7f0:	8b dd                	mov    ebx,ebp
 7f2:	8b ee                	mov    ebp,esi
 7f4:	8b f7                	mov    esi,edi
 7f6:	8b fb                	mov    edi,ebx
 7f8:	8b dd                	mov    ebx,ebp
 7fa:	8b ee                	mov    ebp,esi
 7fc:	8b f7                	mov    esi,edi
 7fe:	8b fb                	mov    edi,ebx
 800:	8b dd                	mov    ebx,ebp
 802:	8b ee                	mov    ebp,esi
 804:	8b f7                	mov    esi,edi
 806:	8b fb                	mov    edi,ebx
 808:	8b dd                	mov    ebx,ebp
 80a:	8b ee                	mov    ebp,esi
 80c:	8b f7                	mov    esi,edi
 80e:	8b fb                	mov    edi,ebx
 810:	8b dd                	mov    ebx,ebp
 812:	8b ee                	mov    ebp,esi
 814:	8b f7                	mov    esi,edi
 816:	8b fb                	mov    edi,ebx
 818:	8b dd                	mov    ebx,ebp
 81a:	8b ee                	mov    ebp,esi
 81c:	8b f7                	mov    esi,edi
 81e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 821:	8b dd                	mov    ebx,ebp
 823:	8b ee                	mov    ebp,esi
 825:	8b f7                	mov    esi,edi
 827:	8b fb                	mov    edi,ebx
 829:	8b dd                	mov    ebx,ebp
 82b:	8b ee                	mov    ebp,esi
 82d:	8b f7                	mov    esi,edi
 82f:	8b fb                	mov    edi,ebx
 831:	8b dd                	mov    ebx,ebp
 833:	8b ee                	mov    ebp,esi
 835:	8b f7                	mov    esi,edi
 837:	8b fb                	mov    edi,ebx
 839:	8b dd                	mov    ebx,ebp
 83b:	8b ee                	mov    ebp,esi
 83d:	8b f7                	mov    esi,edi
 83f:	8b fb                	mov    edi,ebx
 841:	8b dd                	mov    ebx,ebp
 843:	8b ee                	mov    ebp,esi
 845:	8b f7                	mov    esi,edi
 847:	8b fb                	mov    edi,ebx
 849:	8b dd                	mov    ebx,ebp
 84b:	8b ee                	mov    ebp,esi
 84d:	8b f7                	mov    esi,edi
 84f:	8b fb                	mov    edi,ebx
 851:	8b dd                	mov    ebx,ebp
 853:	8b ee                	mov    ebp,esi
 855:	8b f7                	mov    esi,edi
 857:	8b fb                	mov    edi,ebx
 859:	8b dd                	mov    ebx,ebp
 85b:	8b ee                	mov    ebp,esi
 85d:	8b f7                	mov    esi,edi
 85f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 862:	8b dd                	mov    ebx,ebp
 864:	8b ee                	mov    ebp,esi
 866:	8b f7                	mov    esi,edi
 868:	8b fb                	mov    edi,ebx
 86a:	8b dd                	mov    ebx,ebp
 86c:	8b ee                	mov    ebp,esi
 86e:	8b f7                	mov    esi,edi
 870:	8b fb                	mov    edi,ebx
 872:	8b dd                	mov    ebx,ebp
 874:	8b ee                	mov    ebp,esi
 876:	8b f7                	mov    esi,edi
 878:	8b fb                	mov    edi,ebx
 87a:	8b dd                	mov    ebx,ebp
 87c:	8b ee                	mov    ebp,esi
 87e:	8b f7                	mov    esi,edi
 880:	8b fb                	mov    edi,ebx
 882:	8b dd                	mov    ebx,ebp
 884:	8b ee                	mov    ebp,esi
 886:	8b f7                	mov    esi,edi
 888:	8b fb                	mov    edi,ebx
 88a:	8b dd                	mov    ebx,ebp
 88c:	8b ee                	mov    ebp,esi
 88e:	8b f7                	mov    esi,edi
 890:	8b fb                	mov    edi,ebx
 892:	8b dd                	mov    ebx,ebp
 894:	8b ee                	mov    ebp,esi
 896:	8b f7                	mov    esi,edi
 898:	8b fb                	mov    edi,ebx
 89a:	8b dd                	mov    ebx,ebp
 89c:	8b ee                	mov    ebp,esi
 89e:	8b f7                	mov    esi,edi
 8a0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 8a3:	8b dd                	mov    ebx,ebp
 8a5:	8b ee                	mov    ebp,esi
 8a7:	8b f7                	mov    esi,edi
 8a9:	8b fb                	mov    edi,ebx
 8ab:	8b dd                	mov    ebx,ebp
 8ad:	8b ee                	mov    ebp,esi
 8af:	8b f7                	mov    esi,edi
 8b1:	8b fb                	mov    edi,ebx
 8b3:	8b dd                	mov    ebx,ebp
 8b5:	8b ee                	mov    ebp,esi
 8b7:	8b f7                	mov    esi,edi
 8b9:	8b fb                	mov    edi,ebx
 8bb:	8b dd                	mov    ebx,ebp
 8bd:	8b ee                	mov    ebp,esi
 8bf:	8b f7                	mov    esi,edi
 8c1:	8b fb                	mov    edi,ebx
 8c3:	8b dd                	mov    ebx,ebp
 8c5:	8b ee                	mov    ebp,esi
 8c7:	8b f7                	mov    esi,edi
 8c9:	8b fb                	mov    edi,ebx
 8cb:	8b dd                	mov    ebx,ebp
 8cd:	8b ee                	mov    ebp,esi
 8cf:	8b f7                	mov    esi,edi
 8d1:	8b fb                	mov    edi,ebx
 8d3:	8b dd                	mov    ebx,ebp
 8d5:	8b ee                	mov    ebp,esi
 8d7:	8b f7                	mov    esi,edi
 8d9:	8b fb                	mov    edi,ebx
 8db:	8b dd                	mov    ebx,ebp
 8dd:	8b ee                	mov    ebp,esi
 8df:	8b f7                	mov    esi,edi
 8e1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 8e4:	8b dd                	mov    ebx,ebp
 8e6:	8b ee                	mov    ebp,esi
 8e8:	8b f7                	mov    esi,edi
 8ea:	8b fb                	mov    edi,ebx
 8ec:	8b dd                	mov    ebx,ebp
 8ee:	8b ee                	mov    ebp,esi
 8f0:	8b f7                	mov    esi,edi
 8f2:	8b fb                	mov    edi,ebx
 8f4:	8b dd                	mov    ebx,ebp
 8f6:	8b ee                	mov    ebp,esi
 8f8:	8b f7                	mov    esi,edi
 8fa:	8b fb                	mov    edi,ebx
 8fc:	8b dd                	mov    ebx,ebp
 8fe:	8b ee                	mov    ebp,esi
 900:	8b f7                	mov    esi,edi
 902:	8b fb                	mov    edi,ebx
 904:	8b dd                	mov    ebx,ebp
 906:	8b ee                	mov    ebp,esi
 908:	8b f7                	mov    esi,edi
 90a:	8b fb                	mov    edi,ebx
 90c:	8b dd                	mov    ebx,ebp
 90e:	8b ee                	mov    ebp,esi
 910:	8b f7                	mov    esi,edi
 912:	8b fb                	mov    edi,ebx
 914:	8b dd                	mov    ebx,ebp
 916:	8b ee                	mov    ebp,esi
 918:	8b f7                	mov    esi,edi
 91a:	8b fb                	mov    edi,ebx
 91c:	8b dd                	mov    ebx,ebp
 91e:	8b ee                	mov    ebp,esi
 920:	8b f7                	mov    esi,edi
 922:	83 e8 01             	sub    eax,0x1
 925:	0f 85 55 f7 ff ff    	jne    0x80
 92b:	66 90                	xchg   ax,ax
 92d:	66 90                	xchg   ax,ax
 92f:	66 90                	xchg   ax,ax
 931:	66 90                	xchg   ax,ax
 933:	66 90                	xchg   ax,ax
 935:	66 90                	xchg   ax,ax
 937:	66 90                	xchg   ax,ax
 939:	66 90                	xchg   ax,ax
 93b:	48 81 c4 84 35 00 00 	add    rsp,0x3584
 942:	41 59                	pop    r9
 944:	41 58                	pop    r8
 946:	5f                   	pop    rdi
 947:	5e                   	pop    rsi
 948:	5d                   	pop    rbp
 949:	5b                   	pop    rbx
 94a:	0f 77                	emms   
 94c:	c3                   	ret    
