
asm.bin:     file format binary


Disassembly of section .data:

0000000000000000 <.data>:
   0:	66 90                	xchg   ax,ax
   2:	66 90                	xchg   ax,ax
   4:	66 90                	xchg   ax,ax
   6:	66 90                	xchg   ax,ax
   8:	66 90                	xchg   ax,ax
   a:	66 90                	xchg   ax,ax
   c:	66 90                	xchg   ax,ax
   e:	66 90                	xchg   ax,ax
  10:	53                   	push   rbx
  11:	55                   	push   rbp
  12:	56                   	push   rsi
  13:	57                   	push   rdi
  14:	48 b9 00 c0 a0 e7 ff 	movabs rcx,0x7fffe7a0c000
  1b:	7f 00 00 
  1e:	48 ba 00 d0 20 e8 ff 	movabs rdx,0x7fffe820d000
  25:	7f 00 00 
  28:	48 b8 00 20 00 00 00 	movabs rax,0x2000
  2f:	00 00 00 
  32:	48 83 eb 00          	sub    rbx,0x0
  36:	48 83 ed 00          	sub    rbp,0x0
  3a:	48 83 ee 00          	sub    rsi,0x0
  3e:	48 83 ef 00          	sub    rdi,0x0
  42:	49 83 e8 00          	sub    r8,0x0
  46:	49 83 e9 00          	sub    r9,0x0
  4a:	49 83 ea 00          	sub    r10,0x0
  4e:	49 83 eb 00          	sub    r11,0x0
  52:	49 83 ec 00          	sub    r12,0x0
  56:	49 83 ed 00          	sub    r13,0x0
  5a:	49 83 ee 00          	sub    r14,0x0
  5e:	49 83 ef 00          	sub    r15,0x0
  62:	90                   	nop
  63:	90                   	nop
  64:	90                   	nop
  65:	90                   	nop
  66:	90                   	nop
  67:	90                   	nop
  68:	90                   	nop
  69:	90                   	nop
  6a:	90                   	nop
  6b:	90                   	nop
  6c:	90                   	nop
  6d:	90                   	nop
  6e:	90                   	nop
  6f:	90                   	nop
  70:	8b dd                	mov    ebx,ebp
  72:	8b ee                	mov    ebp,esi
  74:	8b f7                	mov    esi,edi
  76:	8b fb                	mov    edi,ebx
  78:	8b dd                	mov    ebx,ebp
  7a:	8b ee                	mov    ebp,esi
  7c:	8b f7                	mov    esi,edi
  7e:	8b fb                	mov    edi,ebx
  80:	8b dd                	mov    ebx,ebp
  82:	8b ee                	mov    ebp,esi
  84:	8b f7                	mov    esi,edi
  86:	8b fb                	mov    edi,ebx
  88:	8b dd                	mov    ebx,ebp
  8a:	8b ee                	mov    ebp,esi
  8c:	8b f7                	mov    esi,edi
  8e:	8b fb                	mov    edi,ebx
  90:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
  93:	8b dd                	mov    ebx,ebp
  95:	8b ee                	mov    ebp,esi
  97:	8b f7                	mov    esi,edi
  99:	8b fb                	mov    edi,ebx
  9b:	8b dd                	mov    ebx,ebp
  9d:	8b ee                	mov    ebp,esi
  9f:	8b f7                	mov    esi,edi
  a1:	8b fb                	mov    edi,ebx
  a3:	8b dd                	mov    ebx,ebp
  a5:	8b ee                	mov    ebp,esi
  a7:	8b f7                	mov    esi,edi
  a9:	8b fb                	mov    edi,ebx
  ab:	8b dd                	mov    ebx,ebp
  ad:	8b ee                	mov    ebp,esi
  af:	8b f7                	mov    esi,edi
  b1:	8b fb                	mov    edi,ebx
  b3:	8b dd                	mov    ebx,ebp
  b5:	8b ee                	mov    ebp,esi
  b7:	8b f7                	mov    esi,edi
  b9:	8b fb                	mov    edi,ebx
  bb:	8b dd                	mov    ebx,ebp
  bd:	8b ee                	mov    ebp,esi
  bf:	8b f7                	mov    esi,edi
  c1:	8b fb                	mov    edi,ebx
  c3:	8b dd                	mov    ebx,ebp
  c5:	8b ee                	mov    ebp,esi
  c7:	8b f7                	mov    esi,edi
  c9:	8b fb                	mov    edi,ebx
  cb:	8b dd                	mov    ebx,ebp
  cd:	8b ee                	mov    ebp,esi
  cf:	8b f7                	mov    esi,edi
  d1:	8b fb                	mov    edi,ebx
  d3:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
  d6:	8b dd                	mov    ebx,ebp
  d8:	8b ee                	mov    ebp,esi
  da:	8b f7                	mov    esi,edi
  dc:	8b fb                	mov    edi,ebx
  de:	8b dd                	mov    ebx,ebp
  e0:	8b ee                	mov    ebp,esi
  e2:	8b f7                	mov    esi,edi
  e4:	8b fb                	mov    edi,ebx
  e6:	8b dd                	mov    ebx,ebp
  e8:	8b ee                	mov    ebp,esi
  ea:	8b f7                	mov    esi,edi
  ec:	8b fb                	mov    edi,ebx
  ee:	8b dd                	mov    ebx,ebp
  f0:	8b ee                	mov    ebp,esi
  f2:	8b f7                	mov    esi,edi
  f4:	8b fb                	mov    edi,ebx
  f6:	8b dd                	mov    ebx,ebp
  f8:	8b ee                	mov    ebp,esi
  fa:	8b f7                	mov    esi,edi
  fc:	8b fb                	mov    edi,ebx
  fe:	8b dd                	mov    ebx,ebp
 100:	8b ee                	mov    ebp,esi
 102:	8b f7                	mov    esi,edi
 104:	8b fb                	mov    edi,ebx
 106:	8b dd                	mov    ebx,ebp
 108:	8b ee                	mov    ebp,esi
 10a:	8b f7                	mov    esi,edi
 10c:	8b fb                	mov    edi,ebx
 10e:	8b dd                	mov    ebx,ebp
 110:	8b ee                	mov    ebp,esi
 112:	8b f7                	mov    esi,edi
 114:	8b fb                	mov    edi,ebx
 116:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 119:	8b dd                	mov    ebx,ebp
 11b:	8b ee                	mov    ebp,esi
 11d:	8b f7                	mov    esi,edi
 11f:	8b fb                	mov    edi,ebx
 121:	8b dd                	mov    ebx,ebp
 123:	8b ee                	mov    ebp,esi
 125:	8b f7                	mov    esi,edi
 127:	8b fb                	mov    edi,ebx
 129:	8b dd                	mov    ebx,ebp
 12b:	8b ee                	mov    ebp,esi
 12d:	8b f7                	mov    esi,edi
 12f:	8b fb                	mov    edi,ebx
 131:	8b dd                	mov    ebx,ebp
 133:	8b ee                	mov    ebp,esi
 135:	8b f7                	mov    esi,edi
 137:	8b fb                	mov    edi,ebx
 139:	8b dd                	mov    ebx,ebp
 13b:	8b ee                	mov    ebp,esi
 13d:	8b f7                	mov    esi,edi
 13f:	8b fb                	mov    edi,ebx
 141:	8b dd                	mov    ebx,ebp
 143:	8b ee                	mov    ebp,esi
 145:	8b f7                	mov    esi,edi
 147:	8b fb                	mov    edi,ebx
 149:	8b dd                	mov    ebx,ebp
 14b:	8b ee                	mov    ebp,esi
 14d:	8b f7                	mov    esi,edi
 14f:	8b fb                	mov    edi,ebx
 151:	8b dd                	mov    ebx,ebp
 153:	8b ee                	mov    ebp,esi
 155:	8b f7                	mov    esi,edi
 157:	8b fb                	mov    edi,ebx
 159:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 15c:	8b dd                	mov    ebx,ebp
 15e:	8b ee                	mov    ebp,esi
 160:	8b f7                	mov    esi,edi
 162:	8b fb                	mov    edi,ebx
 164:	8b dd                	mov    ebx,ebp
 166:	8b ee                	mov    ebp,esi
 168:	8b f7                	mov    esi,edi
 16a:	8b fb                	mov    edi,ebx
 16c:	8b dd                	mov    ebx,ebp
 16e:	8b ee                	mov    ebp,esi
 170:	8b f7                	mov    esi,edi
 172:	8b fb                	mov    edi,ebx
 174:	8b dd                	mov    ebx,ebp
 176:	8b ee                	mov    ebp,esi
 178:	8b f7                	mov    esi,edi
 17a:	8b fb                	mov    edi,ebx
 17c:	8b dd                	mov    ebx,ebp
 17e:	8b ee                	mov    ebp,esi
 180:	8b f7                	mov    esi,edi
 182:	8b fb                	mov    edi,ebx
 184:	8b dd                	mov    ebx,ebp
 186:	8b ee                	mov    ebp,esi
 188:	8b f7                	mov    esi,edi
 18a:	8b fb                	mov    edi,ebx
 18c:	8b dd                	mov    ebx,ebp
 18e:	8b ee                	mov    ebp,esi
 190:	8b f7                	mov    esi,edi
 192:	8b fb                	mov    edi,ebx
 194:	8b dd                	mov    ebx,ebp
 196:	8b ee                	mov    ebp,esi
 198:	8b f7                	mov    esi,edi
 19a:	8b fb                	mov    edi,ebx
 19c:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 19f:	8b dd                	mov    ebx,ebp
 1a1:	8b ee                	mov    ebp,esi
 1a3:	8b f7                	mov    esi,edi
 1a5:	8b fb                	mov    edi,ebx
 1a7:	8b dd                	mov    ebx,ebp
 1a9:	8b ee                	mov    ebp,esi
 1ab:	8b f7                	mov    esi,edi
 1ad:	8b fb                	mov    edi,ebx
 1af:	8b dd                	mov    ebx,ebp
 1b1:	8b ee                	mov    ebp,esi
 1b3:	8b f7                	mov    esi,edi
 1b5:	8b fb                	mov    edi,ebx
 1b7:	8b dd                	mov    ebx,ebp
 1b9:	8b ee                	mov    ebp,esi
 1bb:	8b f7                	mov    esi,edi
 1bd:	8b fb                	mov    edi,ebx
 1bf:	8b dd                	mov    ebx,ebp
 1c1:	8b ee                	mov    ebp,esi
 1c3:	8b f7                	mov    esi,edi
 1c5:	8b fb                	mov    edi,ebx
 1c7:	8b dd                	mov    ebx,ebp
 1c9:	8b ee                	mov    ebp,esi
 1cb:	8b f7                	mov    esi,edi
 1cd:	8b fb                	mov    edi,ebx
 1cf:	8b dd                	mov    ebx,ebp
 1d1:	8b ee                	mov    ebp,esi
 1d3:	8b f7                	mov    esi,edi
 1d5:	8b fb                	mov    edi,ebx
 1d7:	8b dd                	mov    ebx,ebp
 1d9:	8b ee                	mov    ebp,esi
 1db:	8b f7                	mov    esi,edi
 1dd:	8b fb                	mov    edi,ebx
 1df:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 1e2:	8b dd                	mov    ebx,ebp
 1e4:	8b ee                	mov    ebp,esi
 1e6:	8b f7                	mov    esi,edi
 1e8:	8b fb                	mov    edi,ebx
 1ea:	8b dd                	mov    ebx,ebp
 1ec:	8b ee                	mov    ebp,esi
 1ee:	8b f7                	mov    esi,edi
 1f0:	8b fb                	mov    edi,ebx
 1f2:	8b dd                	mov    ebx,ebp
 1f4:	8b ee                	mov    ebp,esi
 1f6:	8b f7                	mov    esi,edi
 1f8:	8b fb                	mov    edi,ebx
 1fa:	8b dd                	mov    ebx,ebp
 1fc:	8b ee                	mov    ebp,esi
 1fe:	8b f7                	mov    esi,edi
 200:	8b fb                	mov    edi,ebx
 202:	8b dd                	mov    ebx,ebp
 204:	8b ee                	mov    ebp,esi
 206:	8b f7                	mov    esi,edi
 208:	8b fb                	mov    edi,ebx
 20a:	8b dd                	mov    ebx,ebp
 20c:	8b ee                	mov    ebp,esi
 20e:	8b f7                	mov    esi,edi
 210:	8b fb                	mov    edi,ebx
 212:	8b dd                	mov    ebx,ebp
 214:	8b ee                	mov    ebp,esi
 216:	8b f7                	mov    esi,edi
 218:	8b fb                	mov    edi,ebx
 21a:	8b dd                	mov    ebx,ebp
 21c:	8b ee                	mov    ebp,esi
 21e:	8b f7                	mov    esi,edi
 220:	8b fb                	mov    edi,ebx
 222:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 225:	8b dd                	mov    ebx,ebp
 227:	8b ee                	mov    ebp,esi
 229:	8b f7                	mov    esi,edi
 22b:	8b fb                	mov    edi,ebx
 22d:	8b dd                	mov    ebx,ebp
 22f:	8b ee                	mov    ebp,esi
 231:	8b f7                	mov    esi,edi
 233:	8b fb                	mov    edi,ebx
 235:	8b dd                	mov    ebx,ebp
 237:	8b ee                	mov    ebp,esi
 239:	8b f7                	mov    esi,edi
 23b:	8b fb                	mov    edi,ebx
 23d:	8b dd                	mov    ebx,ebp
 23f:	8b ee                	mov    ebp,esi
 241:	8b f7                	mov    esi,edi
 243:	8b fb                	mov    edi,ebx
 245:	8b dd                	mov    ebx,ebp
 247:	8b ee                	mov    ebp,esi
 249:	8b f7                	mov    esi,edi
 24b:	8b fb                	mov    edi,ebx
 24d:	8b dd                	mov    ebx,ebp
 24f:	8b ee                	mov    ebp,esi
 251:	8b f7                	mov    esi,edi
 253:	8b fb                	mov    edi,ebx
 255:	8b dd                	mov    ebx,ebp
 257:	8b ee                	mov    ebp,esi
 259:	8b f7                	mov    esi,edi
 25b:	8b fb                	mov    edi,ebx
 25d:	8b dd                	mov    ebx,ebp
 25f:	8b ee                	mov    ebp,esi
 261:	8b f7                	mov    esi,edi
 263:	8b fb                	mov    edi,ebx
 265:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 268:	8b dd                	mov    ebx,ebp
 26a:	8b ee                	mov    ebp,esi
 26c:	8b f7                	mov    esi,edi
 26e:	8b fb                	mov    edi,ebx
 270:	8b dd                	mov    ebx,ebp
 272:	8b ee                	mov    ebp,esi
 274:	8b f7                	mov    esi,edi
 276:	8b fb                	mov    edi,ebx
 278:	8b dd                	mov    ebx,ebp
 27a:	8b ee                	mov    ebp,esi
 27c:	8b f7                	mov    esi,edi
 27e:	8b fb                	mov    edi,ebx
 280:	8b dd                	mov    ebx,ebp
 282:	8b ee                	mov    ebp,esi
 284:	8b f7                	mov    esi,edi
 286:	8b fb                	mov    edi,ebx
 288:	8b dd                	mov    ebx,ebp
 28a:	8b ee                	mov    ebp,esi
 28c:	8b f7                	mov    esi,edi
 28e:	8b fb                	mov    edi,ebx
 290:	8b dd                	mov    ebx,ebp
 292:	8b ee                	mov    ebp,esi
 294:	8b f7                	mov    esi,edi
 296:	8b fb                	mov    edi,ebx
 298:	8b dd                	mov    ebx,ebp
 29a:	8b ee                	mov    ebp,esi
 29c:	8b f7                	mov    esi,edi
 29e:	8b fb                	mov    edi,ebx
 2a0:	8b dd                	mov    ebx,ebp
 2a2:	8b ee                	mov    ebp,esi
 2a4:	8b f7                	mov    esi,edi
 2a6:	8b fb                	mov    edi,ebx
 2a8:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 2ab:	8b dd                	mov    ebx,ebp
 2ad:	8b ee                	mov    ebp,esi
 2af:	8b f7                	mov    esi,edi
 2b1:	8b fb                	mov    edi,ebx
 2b3:	8b dd                	mov    ebx,ebp
 2b5:	8b ee                	mov    ebp,esi
 2b7:	8b f7                	mov    esi,edi
 2b9:	8b fb                	mov    edi,ebx
 2bb:	8b dd                	mov    ebx,ebp
 2bd:	8b ee                	mov    ebp,esi
 2bf:	8b f7                	mov    esi,edi
 2c1:	8b fb                	mov    edi,ebx
 2c3:	8b dd                	mov    ebx,ebp
 2c5:	8b ee                	mov    ebp,esi
 2c7:	8b f7                	mov    esi,edi
 2c9:	8b fb                	mov    edi,ebx
 2cb:	8b dd                	mov    ebx,ebp
 2cd:	8b ee                	mov    ebp,esi
 2cf:	8b f7                	mov    esi,edi
 2d1:	8b fb                	mov    edi,ebx
 2d3:	8b dd                	mov    ebx,ebp
 2d5:	8b ee                	mov    ebp,esi
 2d7:	8b f7                	mov    esi,edi
 2d9:	8b fb                	mov    edi,ebx
 2db:	8b dd                	mov    ebx,ebp
 2dd:	8b ee                	mov    ebp,esi
 2df:	8b f7                	mov    esi,edi
 2e1:	8b fb                	mov    edi,ebx
 2e3:	8b dd                	mov    ebx,ebp
 2e5:	8b ee                	mov    ebp,esi
 2e7:	8b f7                	mov    esi,edi
 2e9:	8b fb                	mov    edi,ebx
 2eb:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 2ee:	8b dd                	mov    ebx,ebp
 2f0:	8b ee                	mov    ebp,esi
 2f2:	8b f7                	mov    esi,edi
 2f4:	8b fb                	mov    edi,ebx
 2f6:	8b dd                	mov    ebx,ebp
 2f8:	8b ee                	mov    ebp,esi
 2fa:	8b f7                	mov    esi,edi
 2fc:	8b fb                	mov    edi,ebx
 2fe:	8b dd                	mov    ebx,ebp
 300:	8b ee                	mov    ebp,esi
 302:	8b f7                	mov    esi,edi
 304:	8b fb                	mov    edi,ebx
 306:	8b dd                	mov    ebx,ebp
 308:	8b ee                	mov    ebp,esi
 30a:	8b f7                	mov    esi,edi
 30c:	8b fb                	mov    edi,ebx
 30e:	8b dd                	mov    ebx,ebp
 310:	8b ee                	mov    ebp,esi
 312:	8b f7                	mov    esi,edi
 314:	8b fb                	mov    edi,ebx
 316:	8b dd                	mov    ebx,ebp
 318:	8b ee                	mov    ebp,esi
 31a:	8b f7                	mov    esi,edi
 31c:	8b fb                	mov    edi,ebx
 31e:	8b dd                	mov    ebx,ebp
 320:	8b ee                	mov    ebp,esi
 322:	8b f7                	mov    esi,edi
 324:	8b fb                	mov    edi,ebx
 326:	8b dd                	mov    ebx,ebp
 328:	8b ee                	mov    ebp,esi
 32a:	8b f7                	mov    esi,edi
 32c:	8b fb                	mov    edi,ebx
 32e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 331:	8b dd                	mov    ebx,ebp
 333:	8b ee                	mov    ebp,esi
 335:	8b f7                	mov    esi,edi
 337:	8b fb                	mov    edi,ebx
 339:	8b dd                	mov    ebx,ebp
 33b:	8b ee                	mov    ebp,esi
 33d:	8b f7                	mov    esi,edi
 33f:	8b fb                	mov    edi,ebx
 341:	8b dd                	mov    ebx,ebp
 343:	8b ee                	mov    ebp,esi
 345:	8b f7                	mov    esi,edi
 347:	8b fb                	mov    edi,ebx
 349:	8b dd                	mov    ebx,ebp
 34b:	8b ee                	mov    ebp,esi
 34d:	8b f7                	mov    esi,edi
 34f:	8b fb                	mov    edi,ebx
 351:	8b dd                	mov    ebx,ebp
 353:	8b ee                	mov    ebp,esi
 355:	8b f7                	mov    esi,edi
 357:	8b fb                	mov    edi,ebx
 359:	8b dd                	mov    ebx,ebp
 35b:	8b ee                	mov    ebp,esi
 35d:	8b f7                	mov    esi,edi
 35f:	8b fb                	mov    edi,ebx
 361:	8b dd                	mov    ebx,ebp
 363:	8b ee                	mov    ebp,esi
 365:	8b f7                	mov    esi,edi
 367:	8b fb                	mov    edi,ebx
 369:	8b dd                	mov    ebx,ebp
 36b:	8b ee                	mov    ebp,esi
 36d:	8b f7                	mov    esi,edi
 36f:	8b fb                	mov    edi,ebx
 371:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 374:	8b dd                	mov    ebx,ebp
 376:	8b ee                	mov    ebp,esi
 378:	8b f7                	mov    esi,edi
 37a:	8b fb                	mov    edi,ebx
 37c:	8b dd                	mov    ebx,ebp
 37e:	8b ee                	mov    ebp,esi
 380:	8b f7                	mov    esi,edi
 382:	8b fb                	mov    edi,ebx
 384:	8b dd                	mov    ebx,ebp
 386:	8b ee                	mov    ebp,esi
 388:	8b f7                	mov    esi,edi
 38a:	8b fb                	mov    edi,ebx
 38c:	8b dd                	mov    ebx,ebp
 38e:	8b ee                	mov    ebp,esi
 390:	8b f7                	mov    esi,edi
 392:	8b fb                	mov    edi,ebx
 394:	8b dd                	mov    ebx,ebp
 396:	8b ee                	mov    ebp,esi
 398:	8b f7                	mov    esi,edi
 39a:	8b fb                	mov    edi,ebx
 39c:	8b dd                	mov    ebx,ebp
 39e:	8b ee                	mov    ebp,esi
 3a0:	8b f7                	mov    esi,edi
 3a2:	8b fb                	mov    edi,ebx
 3a4:	8b dd                	mov    ebx,ebp
 3a6:	8b ee                	mov    ebp,esi
 3a8:	8b f7                	mov    esi,edi
 3aa:	8b fb                	mov    edi,ebx
 3ac:	8b dd                	mov    ebx,ebp
 3ae:	8b ee                	mov    ebp,esi
 3b0:	8b f7                	mov    esi,edi
 3b2:	8b fb                	mov    edi,ebx
 3b4:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 3b7:	8b dd                	mov    ebx,ebp
 3b9:	8b ee                	mov    ebp,esi
 3bb:	8b f7                	mov    esi,edi
 3bd:	8b fb                	mov    edi,ebx
 3bf:	8b dd                	mov    ebx,ebp
 3c1:	8b ee                	mov    ebp,esi
 3c3:	8b f7                	mov    esi,edi
 3c5:	8b fb                	mov    edi,ebx
 3c7:	8b dd                	mov    ebx,ebp
 3c9:	8b ee                	mov    ebp,esi
 3cb:	8b f7                	mov    esi,edi
 3cd:	8b fb                	mov    edi,ebx
 3cf:	8b dd                	mov    ebx,ebp
 3d1:	8b ee                	mov    ebp,esi
 3d3:	8b f7                	mov    esi,edi
 3d5:	8b fb                	mov    edi,ebx
 3d7:	8b dd                	mov    ebx,ebp
 3d9:	8b ee                	mov    ebp,esi
 3db:	8b f7                	mov    esi,edi
 3dd:	8b fb                	mov    edi,ebx
 3df:	8b dd                	mov    ebx,ebp
 3e1:	8b ee                	mov    ebp,esi
 3e3:	8b f7                	mov    esi,edi
 3e5:	8b fb                	mov    edi,ebx
 3e7:	8b dd                	mov    ebx,ebp
 3e9:	8b ee                	mov    ebp,esi
 3eb:	8b f7                	mov    esi,edi
 3ed:	8b fb                	mov    edi,ebx
 3ef:	8b dd                	mov    ebx,ebp
 3f1:	8b ee                	mov    ebp,esi
 3f3:	8b f7                	mov    esi,edi
 3f5:	8b fb                	mov    edi,ebx
 3f7:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 3fa:	8b dd                	mov    ebx,ebp
 3fc:	8b ee                	mov    ebp,esi
 3fe:	8b f7                	mov    esi,edi
 400:	8b fb                	mov    edi,ebx
 402:	8b dd                	mov    ebx,ebp
 404:	8b ee                	mov    ebp,esi
 406:	8b f7                	mov    esi,edi
 408:	8b fb                	mov    edi,ebx
 40a:	8b dd                	mov    ebx,ebp
 40c:	8b ee                	mov    ebp,esi
 40e:	8b f7                	mov    esi,edi
 410:	8b fb                	mov    edi,ebx
 412:	8b dd                	mov    ebx,ebp
 414:	8b ee                	mov    ebp,esi
 416:	8b f7                	mov    esi,edi
 418:	8b fb                	mov    edi,ebx
 41a:	8b dd                	mov    ebx,ebp
 41c:	8b ee                	mov    ebp,esi
 41e:	8b f7                	mov    esi,edi
 420:	8b fb                	mov    edi,ebx
 422:	8b dd                	mov    ebx,ebp
 424:	8b ee                	mov    ebp,esi
 426:	8b f7                	mov    esi,edi
 428:	8b fb                	mov    edi,ebx
 42a:	8b dd                	mov    ebx,ebp
 42c:	8b ee                	mov    ebp,esi
 42e:	8b f7                	mov    esi,edi
 430:	8b fb                	mov    edi,ebx
 432:	8b dd                	mov    ebx,ebp
 434:	8b ee                	mov    ebp,esi
 436:	8b f7                	mov    esi,edi
 438:	8b fb                	mov    edi,ebx
 43a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 43d:	8b dd                	mov    ebx,ebp
 43f:	8b ee                	mov    ebp,esi
 441:	8b f7                	mov    esi,edi
 443:	8b fb                	mov    edi,ebx
 445:	8b dd                	mov    ebx,ebp
 447:	8b ee                	mov    ebp,esi
 449:	8b f7                	mov    esi,edi
 44b:	8b fb                	mov    edi,ebx
 44d:	8b dd                	mov    ebx,ebp
 44f:	8b ee                	mov    ebp,esi
 451:	8b f7                	mov    esi,edi
 453:	8b fb                	mov    edi,ebx
 455:	8b dd                	mov    ebx,ebp
 457:	8b ee                	mov    ebp,esi
 459:	8b f7                	mov    esi,edi
 45b:	8b fb                	mov    edi,ebx
 45d:	8b dd                	mov    ebx,ebp
 45f:	8b ee                	mov    ebp,esi
 461:	8b f7                	mov    esi,edi
 463:	8b fb                	mov    edi,ebx
 465:	8b dd                	mov    ebx,ebp
 467:	8b ee                	mov    ebp,esi
 469:	8b f7                	mov    esi,edi
 46b:	8b fb                	mov    edi,ebx
 46d:	8b dd                	mov    ebx,ebp
 46f:	8b ee                	mov    ebp,esi
 471:	8b f7                	mov    esi,edi
 473:	8b fb                	mov    edi,ebx
 475:	8b dd                	mov    ebx,ebp
 477:	8b ee                	mov    ebp,esi
 479:	8b f7                	mov    esi,edi
 47b:	8b fb                	mov    edi,ebx
 47d:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 480:	8b dd                	mov    ebx,ebp
 482:	8b ee                	mov    ebp,esi
 484:	8b f7                	mov    esi,edi
 486:	8b fb                	mov    edi,ebx
 488:	8b dd                	mov    ebx,ebp
 48a:	8b ee                	mov    ebp,esi
 48c:	8b f7                	mov    esi,edi
 48e:	8b fb                	mov    edi,ebx
 490:	8b dd                	mov    ebx,ebp
 492:	8b ee                	mov    ebp,esi
 494:	8b f7                	mov    esi,edi
 496:	8b fb                	mov    edi,ebx
 498:	8b dd                	mov    ebx,ebp
 49a:	8b ee                	mov    ebp,esi
 49c:	8b f7                	mov    esi,edi
 49e:	8b fb                	mov    edi,ebx
 4a0:	8b dd                	mov    ebx,ebp
 4a2:	8b ee                	mov    ebp,esi
 4a4:	8b f7                	mov    esi,edi
 4a6:	8b fb                	mov    edi,ebx
 4a8:	8b dd                	mov    ebx,ebp
 4aa:	8b ee                	mov    ebp,esi
 4ac:	8b f7                	mov    esi,edi
 4ae:	8b fb                	mov    edi,ebx
 4b0:	8b dd                	mov    ebx,ebp
 4b2:	8b ee                	mov    ebp,esi
 4b4:	8b f7                	mov    esi,edi
 4b6:	8b fb                	mov    edi,ebx
 4b8:	8b dd                	mov    ebx,ebp
 4ba:	8b ee                	mov    ebp,esi
 4bc:	8b f7                	mov    esi,edi
 4be:	8b fb                	mov    edi,ebx
 4c0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 4c3:	8b dd                	mov    ebx,ebp
 4c5:	8b ee                	mov    ebp,esi
 4c7:	8b f7                	mov    esi,edi
 4c9:	8b fb                	mov    edi,ebx
 4cb:	8b dd                	mov    ebx,ebp
 4cd:	8b ee                	mov    ebp,esi
 4cf:	8b f7                	mov    esi,edi
 4d1:	8b fb                	mov    edi,ebx
 4d3:	8b dd                	mov    ebx,ebp
 4d5:	8b ee                	mov    ebp,esi
 4d7:	8b f7                	mov    esi,edi
 4d9:	8b fb                	mov    edi,ebx
 4db:	8b dd                	mov    ebx,ebp
 4dd:	8b ee                	mov    ebp,esi
 4df:	8b f7                	mov    esi,edi
 4e1:	8b fb                	mov    edi,ebx
 4e3:	8b dd                	mov    ebx,ebp
 4e5:	8b ee                	mov    ebp,esi
 4e7:	8b f7                	mov    esi,edi
 4e9:	8b fb                	mov    edi,ebx
 4eb:	8b dd                	mov    ebx,ebp
 4ed:	8b ee                	mov    ebp,esi
 4ef:	8b f7                	mov    esi,edi
 4f1:	8b fb                	mov    edi,ebx
 4f3:	8b dd                	mov    ebx,ebp
 4f5:	8b ee                	mov    ebp,esi
 4f7:	8b f7                	mov    esi,edi
 4f9:	8b fb                	mov    edi,ebx
 4fb:	8b dd                	mov    ebx,ebp
 4fd:	8b ee                	mov    ebp,esi
 4ff:	8b f7                	mov    esi,edi
 501:	8b fb                	mov    edi,ebx
 503:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 506:	8b dd                	mov    ebx,ebp
 508:	8b ee                	mov    ebp,esi
 50a:	8b f7                	mov    esi,edi
 50c:	8b fb                	mov    edi,ebx
 50e:	8b dd                	mov    ebx,ebp
 510:	8b ee                	mov    ebp,esi
 512:	8b f7                	mov    esi,edi
 514:	8b fb                	mov    edi,ebx
 516:	8b dd                	mov    ebx,ebp
 518:	8b ee                	mov    ebp,esi
 51a:	8b f7                	mov    esi,edi
 51c:	8b fb                	mov    edi,ebx
 51e:	8b dd                	mov    ebx,ebp
 520:	8b ee                	mov    ebp,esi
 522:	8b f7                	mov    esi,edi
 524:	8b fb                	mov    edi,ebx
 526:	8b dd                	mov    ebx,ebp
 528:	8b ee                	mov    ebp,esi
 52a:	8b f7                	mov    esi,edi
 52c:	8b fb                	mov    edi,ebx
 52e:	8b dd                	mov    ebx,ebp
 530:	8b ee                	mov    ebp,esi
 532:	8b f7                	mov    esi,edi
 534:	8b fb                	mov    edi,ebx
 536:	8b dd                	mov    ebx,ebp
 538:	8b ee                	mov    ebp,esi
 53a:	8b f7                	mov    esi,edi
 53c:	8b fb                	mov    edi,ebx
 53e:	8b dd                	mov    ebx,ebp
 540:	8b ee                	mov    ebp,esi
 542:	8b f7                	mov    esi,edi
 544:	8b fb                	mov    edi,ebx
 546:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 549:	8b dd                	mov    ebx,ebp
 54b:	8b ee                	mov    ebp,esi
 54d:	8b f7                	mov    esi,edi
 54f:	8b fb                	mov    edi,ebx
 551:	8b dd                	mov    ebx,ebp
 553:	8b ee                	mov    ebp,esi
 555:	8b f7                	mov    esi,edi
 557:	8b fb                	mov    edi,ebx
 559:	8b dd                	mov    ebx,ebp
 55b:	8b ee                	mov    ebp,esi
 55d:	8b f7                	mov    esi,edi
 55f:	8b fb                	mov    edi,ebx
 561:	8b dd                	mov    ebx,ebp
 563:	8b ee                	mov    ebp,esi
 565:	8b f7                	mov    esi,edi
 567:	8b fb                	mov    edi,ebx
 569:	8b dd                	mov    ebx,ebp
 56b:	8b ee                	mov    ebp,esi
 56d:	8b f7                	mov    esi,edi
 56f:	8b fb                	mov    edi,ebx
 571:	8b dd                	mov    ebx,ebp
 573:	8b ee                	mov    ebp,esi
 575:	8b f7                	mov    esi,edi
 577:	8b fb                	mov    edi,ebx
 579:	8b dd                	mov    ebx,ebp
 57b:	8b ee                	mov    ebp,esi
 57d:	8b f7                	mov    esi,edi
 57f:	8b fb                	mov    edi,ebx
 581:	8b dd                	mov    ebx,ebp
 583:	8b ee                	mov    ebp,esi
 585:	8b f7                	mov    esi,edi
 587:	8b fb                	mov    edi,ebx
 589:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 58c:	8b dd                	mov    ebx,ebp
 58e:	8b ee                	mov    ebp,esi
 590:	8b f7                	mov    esi,edi
 592:	8b fb                	mov    edi,ebx
 594:	8b dd                	mov    ebx,ebp
 596:	8b ee                	mov    ebp,esi
 598:	8b f7                	mov    esi,edi
 59a:	8b fb                	mov    edi,ebx
 59c:	8b dd                	mov    ebx,ebp
 59e:	8b ee                	mov    ebp,esi
 5a0:	8b f7                	mov    esi,edi
 5a2:	8b fb                	mov    edi,ebx
 5a4:	8b dd                	mov    ebx,ebp
 5a6:	8b ee                	mov    ebp,esi
 5a8:	8b f7                	mov    esi,edi
 5aa:	8b fb                	mov    edi,ebx
 5ac:	8b dd                	mov    ebx,ebp
 5ae:	8b ee                	mov    ebp,esi
 5b0:	8b f7                	mov    esi,edi
 5b2:	8b fb                	mov    edi,ebx
 5b4:	8b dd                	mov    ebx,ebp
 5b6:	8b ee                	mov    ebp,esi
 5b8:	8b f7                	mov    esi,edi
 5ba:	8b fb                	mov    edi,ebx
 5bc:	8b dd                	mov    ebx,ebp
 5be:	8b ee                	mov    ebp,esi
 5c0:	8b f7                	mov    esi,edi
 5c2:	8b fb                	mov    edi,ebx
 5c4:	8b dd                	mov    ebx,ebp
 5c6:	8b ee                	mov    ebp,esi
 5c8:	8b f7                	mov    esi,edi
 5ca:	8b fb                	mov    edi,ebx
 5cc:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 5cf:	8b dd                	mov    ebx,ebp
 5d1:	8b ee                	mov    ebp,esi
 5d3:	8b f7                	mov    esi,edi
 5d5:	8b fb                	mov    edi,ebx
 5d7:	8b dd                	mov    ebx,ebp
 5d9:	8b ee                	mov    ebp,esi
 5db:	8b f7                	mov    esi,edi
 5dd:	8b fb                	mov    edi,ebx
 5df:	8b dd                	mov    ebx,ebp
 5e1:	8b ee                	mov    ebp,esi
 5e3:	8b f7                	mov    esi,edi
 5e5:	8b fb                	mov    edi,ebx
 5e7:	8b dd                	mov    ebx,ebp
 5e9:	8b ee                	mov    ebp,esi
 5eb:	8b f7                	mov    esi,edi
 5ed:	8b fb                	mov    edi,ebx
 5ef:	8b dd                	mov    ebx,ebp
 5f1:	8b ee                	mov    ebp,esi
 5f3:	8b f7                	mov    esi,edi
 5f5:	8b fb                	mov    edi,ebx
 5f7:	8b dd                	mov    ebx,ebp
 5f9:	8b ee                	mov    ebp,esi
 5fb:	8b f7                	mov    esi,edi
 5fd:	8b fb                	mov    edi,ebx
 5ff:	8b dd                	mov    ebx,ebp
 601:	8b ee                	mov    ebp,esi
 603:	8b f7                	mov    esi,edi
 605:	8b fb                	mov    edi,ebx
 607:	8b dd                	mov    ebx,ebp
 609:	8b ee                	mov    ebp,esi
 60b:	8b f7                	mov    esi,edi
 60d:	8b fb                	mov    edi,ebx
 60f:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 612:	8b dd                	mov    ebx,ebp
 614:	8b ee                	mov    ebp,esi
 616:	8b f7                	mov    esi,edi
 618:	8b fb                	mov    edi,ebx
 61a:	8b dd                	mov    ebx,ebp
 61c:	8b ee                	mov    ebp,esi
 61e:	8b f7                	mov    esi,edi
 620:	8b fb                	mov    edi,ebx
 622:	8b dd                	mov    ebx,ebp
 624:	8b ee                	mov    ebp,esi
 626:	8b f7                	mov    esi,edi
 628:	8b fb                	mov    edi,ebx
 62a:	8b dd                	mov    ebx,ebp
 62c:	8b ee                	mov    ebp,esi
 62e:	8b f7                	mov    esi,edi
 630:	8b fb                	mov    edi,ebx
 632:	8b dd                	mov    ebx,ebp
 634:	8b ee                	mov    ebp,esi
 636:	8b f7                	mov    esi,edi
 638:	8b fb                	mov    edi,ebx
 63a:	8b dd                	mov    ebx,ebp
 63c:	8b ee                	mov    ebp,esi
 63e:	8b f7                	mov    esi,edi
 640:	8b fb                	mov    edi,ebx
 642:	8b dd                	mov    ebx,ebp
 644:	8b ee                	mov    ebp,esi
 646:	8b f7                	mov    esi,edi
 648:	8b fb                	mov    edi,ebx
 64a:	8b dd                	mov    ebx,ebp
 64c:	8b ee                	mov    ebp,esi
 64e:	8b f7                	mov    esi,edi
 650:	8b fb                	mov    edi,ebx
 652:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 655:	8b dd                	mov    ebx,ebp
 657:	8b ee                	mov    ebp,esi
 659:	8b f7                	mov    esi,edi
 65b:	8b fb                	mov    edi,ebx
 65d:	8b dd                	mov    ebx,ebp
 65f:	8b ee                	mov    ebp,esi
 661:	8b f7                	mov    esi,edi
 663:	8b fb                	mov    edi,ebx
 665:	8b dd                	mov    ebx,ebp
 667:	8b ee                	mov    ebp,esi
 669:	8b f7                	mov    esi,edi
 66b:	8b fb                	mov    edi,ebx
 66d:	8b dd                	mov    ebx,ebp
 66f:	8b ee                	mov    ebp,esi
 671:	8b f7                	mov    esi,edi
 673:	8b fb                	mov    edi,ebx
 675:	8b dd                	mov    ebx,ebp
 677:	8b ee                	mov    ebp,esi
 679:	8b f7                	mov    esi,edi
 67b:	8b fb                	mov    edi,ebx
 67d:	8b dd                	mov    ebx,ebp
 67f:	8b ee                	mov    ebp,esi
 681:	8b f7                	mov    esi,edi
 683:	8b fb                	mov    edi,ebx
 685:	8b dd                	mov    ebx,ebp
 687:	8b ee                	mov    ebp,esi
 689:	8b f7                	mov    esi,edi
 68b:	8b fb                	mov    edi,ebx
 68d:	8b dd                	mov    ebx,ebp
 68f:	8b ee                	mov    ebp,esi
 691:	8b f7                	mov    esi,edi
 693:	8b fb                	mov    edi,ebx
 695:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 698:	8b dd                	mov    ebx,ebp
 69a:	8b ee                	mov    ebp,esi
 69c:	8b f7                	mov    esi,edi
 69e:	8b fb                	mov    edi,ebx
 6a0:	8b dd                	mov    ebx,ebp
 6a2:	8b ee                	mov    ebp,esi
 6a4:	8b f7                	mov    esi,edi
 6a6:	8b fb                	mov    edi,ebx
 6a8:	8b dd                	mov    ebx,ebp
 6aa:	8b ee                	mov    ebp,esi
 6ac:	8b f7                	mov    esi,edi
 6ae:	8b fb                	mov    edi,ebx
 6b0:	8b dd                	mov    ebx,ebp
 6b2:	8b ee                	mov    ebp,esi
 6b4:	8b f7                	mov    esi,edi
 6b6:	8b fb                	mov    edi,ebx
 6b8:	8b dd                	mov    ebx,ebp
 6ba:	8b ee                	mov    ebp,esi
 6bc:	8b f7                	mov    esi,edi
 6be:	8b fb                	mov    edi,ebx
 6c0:	8b dd                	mov    ebx,ebp
 6c2:	8b ee                	mov    ebp,esi
 6c4:	8b f7                	mov    esi,edi
 6c6:	8b fb                	mov    edi,ebx
 6c8:	8b dd                	mov    ebx,ebp
 6ca:	8b ee                	mov    ebp,esi
 6cc:	8b f7                	mov    esi,edi
 6ce:	8b fb                	mov    edi,ebx
 6d0:	8b dd                	mov    ebx,ebp
 6d2:	8b ee                	mov    ebp,esi
 6d4:	8b f7                	mov    esi,edi
 6d6:	8b fb                	mov    edi,ebx
 6d8:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 6db:	8b dd                	mov    ebx,ebp
 6dd:	8b ee                	mov    ebp,esi
 6df:	8b f7                	mov    esi,edi
 6e1:	8b fb                	mov    edi,ebx
 6e3:	8b dd                	mov    ebx,ebp
 6e5:	8b ee                	mov    ebp,esi
 6e7:	8b f7                	mov    esi,edi
 6e9:	8b fb                	mov    edi,ebx
 6eb:	8b dd                	mov    ebx,ebp
 6ed:	8b ee                	mov    ebp,esi
 6ef:	8b f7                	mov    esi,edi
 6f1:	8b fb                	mov    edi,ebx
 6f3:	8b dd                	mov    ebx,ebp
 6f5:	8b ee                	mov    ebp,esi
 6f7:	8b f7                	mov    esi,edi
 6f9:	8b fb                	mov    edi,ebx
 6fb:	8b dd                	mov    ebx,ebp
 6fd:	8b ee                	mov    ebp,esi
 6ff:	8b f7                	mov    esi,edi
 701:	8b fb                	mov    edi,ebx
 703:	8b dd                	mov    ebx,ebp
 705:	8b ee                	mov    ebp,esi
 707:	8b f7                	mov    esi,edi
 709:	8b fb                	mov    edi,ebx
 70b:	8b dd                	mov    ebx,ebp
 70d:	8b ee                	mov    ebp,esi
 70f:	8b f7                	mov    esi,edi
 711:	8b fb                	mov    edi,ebx
 713:	8b dd                	mov    ebx,ebp
 715:	8b ee                	mov    ebp,esi
 717:	8b f7                	mov    esi,edi
 719:	8b fb                	mov    edi,ebx
 71b:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 71e:	8b dd                	mov    ebx,ebp
 720:	8b ee                	mov    ebp,esi
 722:	8b f7                	mov    esi,edi
 724:	8b fb                	mov    edi,ebx
 726:	8b dd                	mov    ebx,ebp
 728:	8b ee                	mov    ebp,esi
 72a:	8b f7                	mov    esi,edi
 72c:	8b fb                	mov    edi,ebx
 72e:	8b dd                	mov    ebx,ebp
 730:	8b ee                	mov    ebp,esi
 732:	8b f7                	mov    esi,edi
 734:	8b fb                	mov    edi,ebx
 736:	8b dd                	mov    ebx,ebp
 738:	8b ee                	mov    ebp,esi
 73a:	8b f7                	mov    esi,edi
 73c:	8b fb                	mov    edi,ebx
 73e:	8b dd                	mov    ebx,ebp
 740:	8b ee                	mov    ebp,esi
 742:	8b f7                	mov    esi,edi
 744:	8b fb                	mov    edi,ebx
 746:	8b dd                	mov    ebx,ebp
 748:	8b ee                	mov    ebp,esi
 74a:	8b f7                	mov    esi,edi
 74c:	8b fb                	mov    edi,ebx
 74e:	8b dd                	mov    ebx,ebp
 750:	8b ee                	mov    ebp,esi
 752:	8b f7                	mov    esi,edi
 754:	8b fb                	mov    edi,ebx
 756:	8b dd                	mov    ebx,ebp
 758:	8b ee                	mov    ebp,esi
 75a:	8b f7                	mov    esi,edi
 75c:	8b fb                	mov    edi,ebx
 75e:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 761:	8b dd                	mov    ebx,ebp
 763:	8b ee                	mov    ebp,esi
 765:	8b f7                	mov    esi,edi
 767:	8b fb                	mov    edi,ebx
 769:	8b dd                	mov    ebx,ebp
 76b:	8b ee                	mov    ebp,esi
 76d:	8b f7                	mov    esi,edi
 76f:	8b fb                	mov    edi,ebx
 771:	8b dd                	mov    ebx,ebp
 773:	8b ee                	mov    ebp,esi
 775:	8b f7                	mov    esi,edi
 777:	8b fb                	mov    edi,ebx
 779:	8b dd                	mov    ebx,ebp
 77b:	8b ee                	mov    ebp,esi
 77d:	8b f7                	mov    esi,edi
 77f:	8b fb                	mov    edi,ebx
 781:	8b dd                	mov    ebx,ebp
 783:	8b ee                	mov    ebp,esi
 785:	8b f7                	mov    esi,edi
 787:	8b fb                	mov    edi,ebx
 789:	8b dd                	mov    ebx,ebp
 78b:	8b ee                	mov    ebp,esi
 78d:	8b f7                	mov    esi,edi
 78f:	8b fb                	mov    edi,ebx
 791:	8b dd                	mov    ebx,ebp
 793:	8b ee                	mov    ebp,esi
 795:	8b f7                	mov    esi,edi
 797:	8b fb                	mov    edi,ebx
 799:	8b dd                	mov    ebx,ebp
 79b:	8b ee                	mov    ebp,esi
 79d:	8b f7                	mov    esi,edi
 79f:	8b fb                	mov    edi,ebx
 7a1:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 7a4:	8b dd                	mov    ebx,ebp
 7a6:	8b ee                	mov    ebp,esi
 7a8:	8b f7                	mov    esi,edi
 7aa:	8b fb                	mov    edi,ebx
 7ac:	8b dd                	mov    ebx,ebp
 7ae:	8b ee                	mov    ebp,esi
 7b0:	8b f7                	mov    esi,edi
 7b2:	8b fb                	mov    edi,ebx
 7b4:	8b dd                	mov    ebx,ebp
 7b6:	8b ee                	mov    ebp,esi
 7b8:	8b f7                	mov    esi,edi
 7ba:	8b fb                	mov    edi,ebx
 7bc:	8b dd                	mov    ebx,ebp
 7be:	8b ee                	mov    ebp,esi
 7c0:	8b f7                	mov    esi,edi
 7c2:	8b fb                	mov    edi,ebx
 7c4:	8b dd                	mov    ebx,ebp
 7c6:	8b ee                	mov    ebp,esi
 7c8:	8b f7                	mov    esi,edi
 7ca:	8b fb                	mov    edi,ebx
 7cc:	8b dd                	mov    ebx,ebp
 7ce:	8b ee                	mov    ebp,esi
 7d0:	8b f7                	mov    esi,edi
 7d2:	8b fb                	mov    edi,ebx
 7d4:	8b dd                	mov    ebx,ebp
 7d6:	8b ee                	mov    ebp,esi
 7d8:	8b f7                	mov    esi,edi
 7da:	8b fb                	mov    edi,ebx
 7dc:	8b dd                	mov    ebx,ebp
 7de:	8b ee                	mov    ebp,esi
 7e0:	8b f7                	mov    esi,edi
 7e2:	8b fb                	mov    edi,ebx
 7e4:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 7e7:	8b dd                	mov    ebx,ebp
 7e9:	8b ee                	mov    ebp,esi
 7eb:	8b f7                	mov    esi,edi
 7ed:	8b fb                	mov    edi,ebx
 7ef:	8b dd                	mov    ebx,ebp
 7f1:	8b ee                	mov    ebp,esi
 7f3:	8b f7                	mov    esi,edi
 7f5:	8b fb                	mov    edi,ebx
 7f7:	8b dd                	mov    ebx,ebp
 7f9:	8b ee                	mov    ebp,esi
 7fb:	8b f7                	mov    esi,edi
 7fd:	8b fb                	mov    edi,ebx
 7ff:	8b dd                	mov    ebx,ebp
 801:	8b ee                	mov    ebp,esi
 803:	8b f7                	mov    esi,edi
 805:	8b fb                	mov    edi,ebx
 807:	8b dd                	mov    ebx,ebp
 809:	8b ee                	mov    ebp,esi
 80b:	8b f7                	mov    esi,edi
 80d:	8b fb                	mov    edi,ebx
 80f:	8b dd                	mov    ebx,ebp
 811:	8b ee                	mov    ebp,esi
 813:	8b f7                	mov    esi,edi
 815:	8b fb                	mov    edi,ebx
 817:	8b dd                	mov    ebx,ebp
 819:	8b ee                	mov    ebp,esi
 81b:	8b f7                	mov    esi,edi
 81d:	8b fb                	mov    edi,ebx
 81f:	8b dd                	mov    ebx,ebp
 821:	8b ee                	mov    ebp,esi
 823:	8b f7                	mov    esi,edi
 825:	8b fb                	mov    edi,ebx
 827:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 82a:	8b dd                	mov    ebx,ebp
 82c:	8b ee                	mov    ebp,esi
 82e:	8b f7                	mov    esi,edi
 830:	8b fb                	mov    edi,ebx
 832:	8b dd                	mov    ebx,ebp
 834:	8b ee                	mov    ebp,esi
 836:	8b f7                	mov    esi,edi
 838:	8b fb                	mov    edi,ebx
 83a:	8b dd                	mov    ebx,ebp
 83c:	8b ee                	mov    ebp,esi
 83e:	8b f7                	mov    esi,edi
 840:	8b fb                	mov    edi,ebx
 842:	8b dd                	mov    ebx,ebp
 844:	8b ee                	mov    ebp,esi
 846:	8b f7                	mov    esi,edi
 848:	8b fb                	mov    edi,ebx
 84a:	8b dd                	mov    ebx,ebp
 84c:	8b ee                	mov    ebp,esi
 84e:	8b f7                	mov    esi,edi
 850:	8b fb                	mov    edi,ebx
 852:	8b dd                	mov    ebx,ebp
 854:	8b ee                	mov    ebp,esi
 856:	8b f7                	mov    esi,edi
 858:	8b fb                	mov    edi,ebx
 85a:	8b dd                	mov    ebx,ebp
 85c:	8b ee                	mov    ebp,esi
 85e:	8b f7                	mov    esi,edi
 860:	8b fb                	mov    edi,ebx
 862:	8b dd                	mov    ebx,ebp
 864:	8b ee                	mov    ebp,esi
 866:	8b f7                	mov    esi,edi
 868:	8b fb                	mov    edi,ebx
 86a:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 86d:	8b dd                	mov    ebx,ebp
 86f:	8b ee                	mov    ebp,esi
 871:	8b f7                	mov    esi,edi
 873:	8b fb                	mov    edi,ebx
 875:	8b dd                	mov    ebx,ebp
 877:	8b ee                	mov    ebp,esi
 879:	8b f7                	mov    esi,edi
 87b:	8b fb                	mov    edi,ebx
 87d:	8b dd                	mov    ebx,ebp
 87f:	8b ee                	mov    ebp,esi
 881:	8b f7                	mov    esi,edi
 883:	8b fb                	mov    edi,ebx
 885:	8b dd                	mov    ebx,ebp
 887:	8b ee                	mov    ebp,esi
 889:	8b f7                	mov    esi,edi
 88b:	8b fb                	mov    edi,ebx
 88d:	8b dd                	mov    ebx,ebp
 88f:	8b ee                	mov    ebp,esi
 891:	8b f7                	mov    esi,edi
 893:	8b fb                	mov    edi,ebx
 895:	8b dd                	mov    ebx,ebp
 897:	8b ee                	mov    ebp,esi
 899:	8b f7                	mov    esi,edi
 89b:	8b fb                	mov    edi,ebx
 89d:	8b dd                	mov    ebx,ebp
 89f:	8b ee                	mov    ebp,esi
 8a1:	8b f7                	mov    esi,edi
 8a3:	8b fb                	mov    edi,ebx
 8a5:	8b dd                	mov    ebx,ebp
 8a7:	8b ee                	mov    ebp,esi
 8a9:	8b f7                	mov    esi,edi
 8ab:	8b fb                	mov    edi,ebx
 8ad:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 8b0:	8b dd                	mov    ebx,ebp
 8b2:	8b ee                	mov    ebp,esi
 8b4:	8b f7                	mov    esi,edi
 8b6:	8b fb                	mov    edi,ebx
 8b8:	8b dd                	mov    ebx,ebp
 8ba:	8b ee                	mov    ebp,esi
 8bc:	8b f7                	mov    esi,edi
 8be:	8b fb                	mov    edi,ebx
 8c0:	8b dd                	mov    ebx,ebp
 8c2:	8b ee                	mov    ebp,esi
 8c4:	8b f7                	mov    esi,edi
 8c6:	8b fb                	mov    edi,ebx
 8c8:	8b dd                	mov    ebx,ebp
 8ca:	8b ee                	mov    ebp,esi
 8cc:	8b f7                	mov    esi,edi
 8ce:	8b fb                	mov    edi,ebx
 8d0:	8b dd                	mov    ebx,ebp
 8d2:	8b ee                	mov    ebp,esi
 8d4:	8b f7                	mov    esi,edi
 8d6:	8b fb                	mov    edi,ebx
 8d8:	8b dd                	mov    ebx,ebp
 8da:	8b ee                	mov    ebp,esi
 8dc:	8b f7                	mov    esi,edi
 8de:	8b fb                	mov    edi,ebx
 8e0:	8b dd                	mov    ebx,ebp
 8e2:	8b ee                	mov    ebp,esi
 8e4:	8b f7                	mov    esi,edi
 8e6:	8b fb                	mov    edi,ebx
 8e8:	8b dd                	mov    ebx,ebp
 8ea:	8b ee                	mov    ebp,esi
 8ec:	8b f7                	mov    esi,edi
 8ee:	8b fb                	mov    edi,ebx
 8f0:	48 8b 09             	mov    rcx,QWORD PTR [rcx]
 8f3:	8b dd                	mov    ebx,ebp
 8f5:	8b ee                	mov    ebp,esi
 8f7:	8b f7                	mov    esi,edi
 8f9:	8b fb                	mov    edi,ebx
 8fb:	8b dd                	mov    ebx,ebp
 8fd:	8b ee                	mov    ebp,esi
 8ff:	8b f7                	mov    esi,edi
 901:	8b fb                	mov    edi,ebx
 903:	8b dd                	mov    ebx,ebp
 905:	8b ee                	mov    ebp,esi
 907:	8b f7                	mov    esi,edi
 909:	8b fb                	mov    edi,ebx
 90b:	8b dd                	mov    ebx,ebp
 90d:	8b ee                	mov    ebp,esi
 90f:	8b f7                	mov    esi,edi
 911:	8b fb                	mov    edi,ebx
 913:	8b dd                	mov    ebx,ebp
 915:	8b ee                	mov    ebp,esi
 917:	8b f7                	mov    esi,edi
 919:	8b fb                	mov    edi,ebx
 91b:	8b dd                	mov    ebx,ebp
 91d:	8b ee                	mov    ebp,esi
 91f:	8b f7                	mov    esi,edi
 921:	8b fb                	mov    edi,ebx
 923:	8b dd                	mov    ebx,ebp
 925:	8b ee                	mov    ebp,esi
 927:	8b f7                	mov    esi,edi
 929:	8b fb                	mov    edi,ebx
 92b:	8b dd                	mov    ebx,ebp
 92d:	8b ee                	mov    ebp,esi
 92f:	8b f7                	mov    esi,edi
 931:	8b fb                	mov    edi,ebx
 933:	48 8b 12             	mov    rdx,QWORD PTR [rdx]
 936:	8b dd                	mov    ebx,ebp
 938:	8b ee                	mov    ebp,esi
 93a:	8b f7                	mov    esi,edi
 93c:	8b fb                	mov    edi,ebx
 93e:	8b dd                	mov    ebx,ebp
 940:	8b ee                	mov    ebp,esi
 942:	8b f7                	mov    esi,edi
 944:	8b fb                	mov    edi,ebx
 946:	8b dd                	mov    ebx,ebp
 948:	8b ee                	mov    ebp,esi
 94a:	8b f7                	mov    esi,edi
 94c:	8b fb                	mov    edi,ebx
 94e:	8b dd                	mov    ebx,ebp
 950:	8b ee                	mov    ebp,esi
 952:	8b f7                	mov    esi,edi
 954:	83 e8 01             	sub    eax,0x1
 957:	0f 85 13 f7 ff ff    	jne    0x70
 95d:	66 90                	xchg   ax,ax
 95f:	66 90                	xchg   ax,ax
 961:	66 90                	xchg   ax,ax
 963:	66 90                	xchg   ax,ax
 965:	66 90                	xchg   ax,ax
 967:	66 90                	xchg   ax,ax
 969:	66 90                	xchg   ax,ax
 96b:	66 90                	xchg   ax,ax
 96d:	5f                   	pop    rdi
 96e:	5e                   	pop    rsi
 96f:	5d                   	pop    rbp
 970:	5b                   	pop    rbx
 971:	0f 77                	emms   
 973:	c3                   	ret    
